### ISSUE TITLE
Multi-Release JAR Files

### ISSUE THREAD

**Issue by JonathanGiles** [controlsfx/controlsfx#1014]
**[Original report](https://bitbucket.org/controlsfx/controlsfx/issue/823) by Austin Shalit (Bitbucket: [AustinShalit](https://bitbucket.org/AustinShalit), GitHub: [AustinShalit](https://github.com/AustinShalit)).**

----------------------------------------

Right now it is hard to publish an application that uses ControlsFX for both Java 8 and Java 9.  ControlsFX should look into publishing a Multi-Release JAR File that would support both Java 8 and Java 9.

http://openjdk.java.net/jeps/238

**Comment by Glavo** [comment]
Hey, any progress on this issue? After the introduction of toolchain in Gradle 6.7, I think this feature is easier to implement.

It's frustrating that my program can't work on Java 8, but it's even worse if it only supports Java 8. I hope to make the program easily compatible with all versions after Java 8 while using controlsfx.

**Comment by abhinayagarwal** [comment]
There are no plans to support multi-release jars. For Java 8 and 11, please use ControlsFX 8.x.x and 11.x.x respectively,

**Comment by oowekyala** [comment]
I'm sad to see this will not be supported. FWIW [pmd/pmd-designer](https://github.com/pmd/pmd-designer/blob/master/lib/pom.xml) builds it own multi-release jar with Maven as a workaround. Maybe this can help others: https://github.com/pmd/pmd-designer/blob/master/lib/pom.xml
