### ISSUE TITLE
StatusBar no longer shows cycling ProgressBar - JDK 9

### ISSUE THREAD

**Issue by JonathanGiles** [controlsfx/controlsfx#1018]
**[Original report](https://bitbucket.org/controlsfx/controlsfx/issue/827) by Adam Carroll (Bitbucket: [Adam-Bitbucket](https://bitbucket.org/Adam-Bitbucket), GitHub: Unknown).**

----------------------------------------

There seems to be a regression of issue #794 in v9.0.0 of ControlsFX under JDK 9.0.1.  The symptoms are exactly those described in #794 (including screenshots).  Again, the issue can be reproduced using the sample app.

**Comment by abhinayagarwal** [comment]
Fixed by [PR #643](https://bitbucket.org/controlsfx/controlsfx/pull-requests/643)
