### ISSUE TITLE
CheckComboBox documentation's bad example

### ISSUE THREAD

**Issue by JonathanGiles** [controlsfx/controlsfx#1021]
**[Original report](https://bitbucket.org/controlsfx/controlsfx/issue/830) by Bradley Turek (Bitbucket: [UgmaDevelopment](https://bitbucket.org/UgmaDevelopment), GitHub: [UgmaDevelopment](https://github.com/UgmaDevelopment)).**

----------------------------------------

In the [documentation of CheckComboBox](https://controlsfx.bitbucket.io/org/controlsfx/control/CheckComboBox.html) the, otherwise helpful, example is written:

```
#!java

// and listen to the relevant events (e.g. when the selected indices or 
 // selected items change).
 checkComboBox.getCheckModel().getCheckedItems().addListener(new ListChangeListener<String>() {
     public void onChanged(ListChangeListener.Change<? extends String> c) {
         System.out.println(checkComboBox.getCheckModel().getSelectedItems());
     }
 });
```

The problem here is that `getSelectedItems()` is not a method.

**The correct method is `getCheckedItems()`.**

I bring it up because it could prove blocking to new users. 

It surely took me a not-so-quick minute to figure it out.

**Comment by Maxoudela** [comment]
Please review pull request #1207
