### ISSUE TITLE
CheckComboBox ListChangeListener fires off twice after selection change

### ISSUE THREAD

**Issue by JonathanGiles** [controlsfx/controlsfx#1030]
**[Original report](https://bitbucket.org/controlsfx/controlsfx/issue/839) by FanFeeds (Bitbucket: [user3822](https://bitbucket.org/user3822), GitHub: Unknown).**

----------------------------------------

I'm using a custom ControlsFX that has [Pull Request #677](https://bitbucket.org/controlsfx/controlsfx/pull-requests/677) which adds the ability to click on the label next to the checkbox in order to select the item.

After some testing, I believe it comes down to the changes made in this pull request, and I'll explain why.

Here's what my test code looks like:
       
```
#!java

checkComboBox.getCheckModel().getCheckedItems().addListener(new ListChangeListener<String>() {
    @Override
    public void onChanged(ListChangeListener.Change<? extends String> c) {
        while (c.next()){
            System.out.println("test");
        }
    }
});       
```

After a few hours of testing, I found out that if I click directly on the checkbox, it only fires off once. But if I click on the label to the right of the checkbox, it fires off twice.

I also created a separate project with the publicly available ControlsFX and tried it out. It works properly (which, considering my previous testing, it should work properly because the label on the right cannot be clicked in order to select the checkbox).

Put it all together, and I think the culprit lies somewhere in the changes made in Pull Request #677.

Happy Holidays and take care, everyone!

**Comment by hink084** [comment]
This is still a bug in v11.0.3.  I am unable to find the referenced PR's associated with this issue.

**Comment by triathematician** [comment]
In my application, this causes an array index error when clicking on the label adjacent to the check. (I have a downstream listener, and there is a -1 used for array index in one of the nested list update calls.)

I was able to fix the issue -- so it only fires once and fixing my index exception -- by changing the clearCheck() and check() methods in `CheckBitSetModelBase`, which are invoked when you click on labels, as follows:

```java
    /** {@inheritDoc} */
    @Override public void clearCheck(T item) {
        getItemBooleanProperty(item).set(false);
//        int index = getItemIndex(item);
//        clearCheck(index);
    }

    /** {@inheritDoc} */
    @Override
    public void check(T item) {
        getItemBooleanProperty(item).set(true);
//        int index = getItemIndex(item);
//        check(index);
    }
```

**Comment by lsh-0** [comment]
thanks to @JonathanGiles for investigating the problem and raising this ticket, I'm seeing this behaviour too in `11.1.1`.

**Comment by nickpotafiy** [comment]
Still an issue in 11.1.2

**Comment by abhinayagarwal** [comment]
@nickpotafiy @lsh-0 Please review #1472 and see if it fixes the issue?
