### ISSUE TITLE
Can't open project in Eclipse

### ISSUE THREAD

**Issue by JonathanGiles** [controlsfx/controlsfx#1057]
**[Original report](https://bitbucket.org/controlsfx/controlsfx/issue/866) by Mikael Wallin (Bitbucket: [miwashi](https://bitbucket.org/miwashi), GitHub: Unknown).**

----------------------------------------

As root project is named same as a subproject, Eclipse claims project already imported when importing project.

Eclipse Oxygen.3a Release (4.7.3a)
Buildship 2.2.1

**Comment by abhinayagarwal** [comment]
Duplicate of #937.
