### ISSUE TITLE
Migrate code to GitHub

### ISSUE THREAD

**Issue by JonathanGiles** [controlsfx/controlsfx#1084]
**[Original report](https://bitbucket.org/controlsfx/controlsfx/issue/893) by Andres Almiray (Bitbucket: [aalmiray](https://bitbucket.org/aalmiray), GitHub: [aalmiray](https://github.com/aalmiray)).**

----------------------------------------

It would be great to move the code to GitHub as it has a much wider spread in the developer community.

**Comment by Maxoudela** [comment]
Please note that my Github account is "maxoudela" and my Bitbucket account is "shadzic". The @shadzic account on Github belongs to a member of my family but it's not mine :)

**Comment by JonathanGiles** [comment]
Sorry about that. The script I used tried its best but clearly failed in some cases. There is nothing I can do to fix this now without wiping the repo, fixing it, and doing it over, and I don't think that this makes sense now.
