### ISSUE TITLE
some of the *.controlsfx.org can't be opened

### ISSUE THREAD

**Issue by silentsoft** [controlsfx/controlsfx#1090]
I'd like to contribute to controlsfx, but some of the links on [bitbucket wiki](https://bitbucket.org/controlsfx/controlsfx/wiki/Home) can't be opened.

http://cla.controlsfx.org
http://groups.controlsfx.org
http://i18n.controlsfx.org

it may seems lost about A record.

```
MacBook-Air:~ silentsoft$ nslookup cla.controlsfx.org
Server:		168.126.63.1
Address:	168.126.63.1#53

** server can't find cla.controlsfx.org: NXDOMAIN

MacBook-Air:~ silentsoft$ nslookup groups.controlsfx.org
Server:		168.126.63.1
Address:	168.126.63.1#53

** server can't find groups.controlsfx.org: NXDOMAIN

MacBook-Air:~ silentsoft$ nslookup i18n.controlsfx.org
Server:		168.126.63.1
Address:	168.126.63.1#53

** server can't find i18n.controlsfx.org: NXDOMAIN

MacBook-Air:~ silentsoft$ nslookup controlsfx.org
Server:		168.126.63.1
Address:	168.126.63.1#53

Non-authoritative answer:
Name:	controlsfx.org
Address: 104.27.153.88
Name:	controlsfx.org
Address: 104.27.152.88
```

**Comment by abhinayagarwal** [comment]
@JonathanGiles Any idea if we have replacements for these links?

**Comment by JonathanGiles** [comment]
I'm working with the DNS provider to get more page rules, so that these can be reinstated. Otherwise it'll cost me monthly to have these, which I probably wouldn't do. Updating the wiki to link direct to these pages is the best option - I will find the links.

**Comment by JonathanGiles** [comment]
I've subscribed to have more page rules with cloudflare, and have added these missing redirects. Hopefully once the DNS details propagate this should work as expected.

**Comment by JonathanGiles** [comment]
Btw - it would be great if you ported the wiki from bitbucket into github too!

**Comment by silentsoft** [comment]
oh, the links are works !
