### ISSUE TITLE
Download for ControlsFX java 8 not working

### ISSUE THREAD

**Issue by KyleRAnderson** [controlsfx/controlsfx#1093]
The download link for ControlsFX for java 8 in the README doesn't work.

**Comment by ToniSoftware** [comment]
Hey, just remove the ' " ' at the end
http://fxexperience.com/downloads/controlsfx-8-40-14/"

**Comment by KyleRAnderson** [comment]
That did it, thanks.

**Comment by JonathanGiles** [comment]
Fixed it, thanks.
