### ISSUE TITLE
ListSelectionView broken in 8.40.15

### ISSUE THREAD

**Issue by shanrak** [controlsfx/controlsfx#1097]
In 8.40.15 the list selection view lists (target and source lists) seems to have stopped updating.  Here is sample code demonstrating the problem:

```
package playing;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import org.controlsfx.control.ListSelectionView;

import javafx.application.Platform;
import javafx.collections.FXCollections;
import javafx.embed.swing.JFXPanel;
import javafx.geometry.Orientation;
import javafx.scene.control.ButtonType;
import javafx.scene.control.Dialog;
import javafx.util.Callback;

public class Playing
{
    private ListSelectionView<String> view;

    public Playing()
    {
        setup();
    }

    private void setup()
    {

        List<String> list = new ArrayList<>();
        list.add("A");
        list.add("B");
        list.add("C");
        list.add("D");
        view = new ListSelectionView<>();

        view.setOrientation(Orientation.HORIZONTAL);

        MyResultConverter resultConverter = new MyResultConverter();

        view.setTargetItems(FXCollections.observableList(list));

        Platform.runLater(() ->
        {
            Dialog<List<String>> fxDialog = new Dialog<>();
            fxDialog.setTitle("Select");
            fxDialog.getDialogPane().getButtonTypes().addAll(ButtonType.OK, ButtonType.CANCEL);
            fxDialog.getDialogPane().setContent(view);
            fxDialog.setResultConverter(resultConverter);
            fxDialog.setOnCloseRequest(e -> processResults(fxDialog.getResult()));
            fxDialog.show();
        });

    }

    public static void main(String[] args)
    {
        new JFXPanel();
        new Playing();
        try
        {
            Thread.sleep(30000);
        }
        catch (InterruptedException e)
        {
            Thread.currentThread().interrupt();
        }
    }

    /**
     * 
     * This callback is used by the dialog when the user hits the ok/cancel buttons
     * 
     * 
     */

    private class MyResultConverter implements Callback<ButtonType, List<String>>
    {
        @Override
        public List<String> call(ButtonType b)
        {
            if (b == ButtonType.OK)
            {
                System.out.println("Sources: ");
                view.getSourceItems().forEach(e -> System.out.print(e + "|"));
                return view.getTargetItems();
            }
            else
            {
                return Collections.emptyList();
            }
        }
    }

    private void processResults(List<String> list)
    {
        System.out.println("Result: ");
        list.stream().forEach(f -> System.out.println(f));
    }

}
```

When you run the dialog and modify the list, the result always print A B C D for the target list.  Reverting back to 8.40.14 fixes it.

**Comment by graynk** [comment]
Broken in 11.0.0-RC2 as well.

**Comment by abhinayagarwal** [comment]
Please test PR #1117 to check if the bug is fixed.

**Comment by cbackas** [comment]
Has this issue been fixed? I'm using the maven central version of controlsfx 11.0.0.

I set my source list with `lsv_selectContacts.getSourceItems().setAll(nonClientContacts);`

and then when I click the arrow buttons to move items between the source and target lists, they visually change but calling `lsv_selectContacts.getSourceItems()` ALWAYS returns the original set of items I set originally and `lsv_selectContacts.getTargetItems()` ALWAYS returns an empty list, regardless of where the items are visually in the list. Am I doing something wrong here or is this still broken?

**Comment by bezvaapp** [comment]
It seems to be broken on 11.0.0. The changes from source and target are propagated to the list views but in the opposite direction the changes are not propagated so it is not possible to get the actual selection.

**Comment by abhinayagarwal** [comment]
I am not sure why, but it seems both `8.40.15` and `11.0.0` does not have the fix in them. Can someone build from the source and check if it fixes the issue for them?

**Comment by ViniciusSSilva** [comment]
> I am not sure why, but it seems both `8.40.15` and `11.0.0` does not have the fix in them. Can someone build from the source and check if it fixes the issue for them?

The `11.0.0` Release was done before #1117 bug-fix

I found a way to fix it using https://jitpack.io

add the arg: `--add-exports=javafx.base/com.sun.javafx.runtime=ALL-UNNAMED`

pom.xml changes (with maven):
```xml
<repositories>
     <repository>
          <id>jitpack.io</id>
          <url>https://jitpack.io</url>
     </repository>
</repositories>
...
<dependencies>
    ...
    <!-- ControlsFx Release Jul 08, 2019 -->
    <dependency>
        <groupId>com.github.abhinayagarwal.controlsfx</groupId>
        <artifactId>controlsfx</artifactId>
        <version>-cdad7beeb2-1</version>
    </dependency>
    ...
</dependencies>

**Comment by bezvaapp** [comment]
It seems working in version -cdad7beeb2-1.

**Comment by abhinayagarwal** [comment]
@ViniciusSSilva Ah, my bad. I was checking the date of commit instead of the date of merge.

If someone wants to try out the latest version, we release [snapshot versions for ControlsFX](https://oss.sonatype.org/content/repositories/snapshots/org/controlsfx/controlsfx/).

**Comment by chibsta** [comment]
Thanks @abhinayagarwal! I just added the 8.40.16-20191104.100139-31 version dependency from the link you provided to my build.gradle and that sorts out the problem. For gradle newbies (like me) you need to:

1. Add the maven url https://oss.sonatype.org/content/repositories/snapshots/ to your gradle repositories
2. Then add `compile group: 'org.controlsfx', name: 'controlsfx', version: '8.40.16-20191104.100139-31'` to the dependencies tag, substituting the version number as necessary.

Then reload/rebuild your project

**Comment by abhinayagarwal** [comment]
@chibsta Correction: The dependency doesn't need to specify a particular snapshot version number. You can just specify the version as `8.40.16-SNAPSHOT`:
```
compile group: 'org.controlsfx', name: 'controlsfx', version: '8.40.16-SNAPSHOT'
```
