### ISSUE TITLE
Update CI to use Travis

### ISSUE THREAD

**Issue by abhinayagarwal** [controlsfx/controlsfx#1102]
With recent move to Github, we can no longer use Bitbucket pipelines. All CI pipeline related code should be updated to use Travis CI instead.

**Comment by JonathanGiles** [comment]
I'd like to use Azure Pipelines instead :)

**Comment by abhinayagarwal** [comment]
This has already been implemented :)

We are now running sanity test on PRs and releasing snapshots using Travis CI.
