### ISSUE TITLE
BreadCrumbBar setCrumbFactory not usable

### ISSUE THREAD

**Issue by hbrackmann** [controlsfx/controlsfx#1109]
BreadCrumbBar setCrumbFactory ist not usable because BreadCrumbButton ist not accessible.
Realistically BreadCrumbBar only works with BreadCrumbButtons.
Its's already discussed https://github.com/controlsfx/controlsfx/issues/971

version: '11.0.0-RC2'

**Comment by abhinayagarwal** [comment]
We can place the static class `BreadCrumbButton` inside `BreadCrumbBar`. This way it stays as a part of `BreadCrumbBar` and can be used for inside `setCrumbFactory`. Thoughts?

cc @JonathanGiles @puce77

**Comment by Maxoudela** [comment]
CLA has been signed, thanks.
