### ISSUE TITLE
Add code-of-conduct file

### ISSUE THREAD

**Issue by Ciruman** [controlsfx/controlsfx#1111]
I think it would be good to have a file code-of conduct.md here, like this one:
https://www.contributor-covenant.org/version/1/4/code-of-conduct

**Comment by abhinayagarwal** [comment]
@Ciruman Can you create a PR? :)

**Comment by Ciruman** [comment]
> @Ciruman Can you create a PR? :)

I need a default contact email.

**Comment by abhinayagarwal** [comment]
You can most probably use mine: abhinay_agarwal@live.com

In case @JonathanGiles wants his, we can update the CoC :)
