### ISSUE TITLE
Java11 OSGi Manifest imports cause errors in e(fx)clipse

### ISSUE THREAD

**Issue by SimonScholz** [controlsfx/controlsfx#1119]
Hi,

I am working on an e(fx)clipse rcp project and want to make use of ControlsFx, but the following line causes errors, since these imports are not really available and provided differently in the classpath by e(fx)clipse.

https://github.com/controlsfx/controlsfx/blob/272f5541dc35bf183acbc544016fe07099989ec2/controlsfx/build.gradle#L111

I think you should simply import nothing by omitting Line 111 from above and the problems should go away.

**Comment by Maxoudela** [comment]
Related to #1191
