### ISSUE TITLE
Problems in the example codes

### ISSUE THREAD

**Issue by clutchyu** [controlsfx/controlsfx#1128]
I tried the example codes HelloSpreadsheetView.java, but the class named ControlsFXSample can not be found in it.I believe it's becase of the versions,may you show me a solution to show the sample?Without sample,I can hardly use the SpreadsheetView,Thanks a lot.

**Comment by abhinayagarwal** [comment]
Which version on ControlsFX are you on?

**Comment by clutchyu** [comment]
8.40.14-------- 原始邮件 --------主题：Re: [controlsfx/controlsfx] Problems in the example codes (#1128)发件人：Abhinay Agarwal 收件人：controlsfx/controlsfx 抄送：王禹 ,Author Which version on ControlsFX are you on?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/controlsfx/controlsfx","title":"controlsfx/controlsfx","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/controlsfx/controlsfx"}},"updates":{"snippets":[{"icon":"PERSON","message":"@abhinayagarwal in #1128: Which version on ControlsFX are you on?"}],"action":{"name":"View Issue","url":"https://github.com/controlsfx/controlsfx/issues/1128#issuecomment-478537493"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/controlsfx/controlsfx/issues/1128#issuecomment-478537493",
"url": "https://github.com/controlsfx/controlsfx/issues/1128#issuecomment-478537493",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by abhinayagarwal** [comment]
With 8.40.14, `HelloSpreadsheetView.java` should work fine. Can you list the steps you are using to run the sample?

**Comment by clutchyu** [comment]
Sorry,I will check the version later.If it has problem still,I will list the steps.Thanks for your help.-------- 原始邮件 --------主题：Re: [controlsfx/controlsfx] Problems in the example codes (#1128)发件人：Abhinay Agarwal 收件人：controlsfx/controlsfx 抄送：王禹 ,Author With 8.40.14, HelloSpreadsheetView.java should work fine. Can you list the steps you are using to run the sample?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/controlsfx/controlsfx","title":"controlsfx/controlsfx","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/controlsfx/controlsfx"}},"updates":{"snippets":[{"icon":"PERSON","message":"@abhinayagarwal in #1128: With 8.40.14, `HelloSpreadsheetView.java` should work fine. Can you list the steps you are using to run the sample?"}],"action":{"name":"View Issue","url":"https://github.com/controlsfx/controlsfx/issues/1128#issuecomment-478557010"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/controlsfx/controlsfx/issues/1128#issuecomment-478557010",
"url": "https://github.com/controlsfx/controlsfx/issues/1128#issuecomment-478557010",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by clutchyu** [comment]
I hava just tried again,the version is 8.40.14.I add the jar as the Referenced Libraries in eclipse,open the HelloSpreadsheetView.java,and next show in the picture
![image](https://user-images.githubusercontent.com/25337475/55332637-623f0380-54c8-11e9-8c0f-904674fe7471.png).So,is my step wrong?Thanks.

**Comment by clutchyu** [comment]
I'm sorry,it's my own fault.I haven't add the controlsfx-sample.jar,when I added it,it succeed.Thanks a lot.
