### ISSUE TITLE
Unable to set text fill for ToggleSwitch

### ISSUE THREAD

**Issue by Mason-Chou** [controlsfx/controlsfx#1144]
I can't set the text fill for any toggle switches. Neither setting it in the Java code or in a css file will set the text fill color. Below is what I've tried so far.

Hardcoded in Java source file:
```java
ToggleSwitch toggle = new ToggleSwitch("Test");
toggle.setFont(Font.of("arial", 16));
toggle.setTextFill(Paint.valueOf("red"));
```

In a external css file:
```java
// Assume that the parent scene has already loaded the css file.
ToggleSwitch toggle = new ToggleSwitch("Test");
toggle.getStyleClass().add("colored-toggle-switch");
```

```css
.colored-toggle-switch {
    -fx-font: 16px arial;
    -fx-text-fill: red;
}
```

The above will change the font of the text for the toggle switch, but not the color of the text.

I'm using ControlsFX 8 if it matters, but I think the issue is due to this [line of code](https://github.com/controlsfx/controlsfx/blob/0710e9fe4ea705f70282886381de25e2fe9bf11c/controlsfx/src/main/resources/org/controlsfx/control/toggleswitch.css#L12)  in the default theme. Any help is appreciated.

**Comment by abhinayagarwal** [comment]
Can you try:

```
.colored-toggle-switch .text {
    -fx-font: 16px arial;
    -fx-text-fill: red;
}

**Comment by Mason-Chou** [comment]
> Can you try:
> 
> ```
> .colored-toggle-switch .text {
>     -fx-font: 16px arial;
>     -fx-text-fill: red;
> }
> ```

Still has the same issue. font has changed, but not the color of the text.

**Comment by abhinayagarwal** [comment]
Sorry. Should have tried before posting. Can you try:
```
.colored-toggle-switch .label {
    -fx-font: 16px arial;
    -fx-text-fill: red;
}
```

**Comment by Mason-Chou** [comment]
Works for me too! Good workaround for the problem. Thanks @abhinayagarwal! 

Going to leave this issue open as the original issue is a bug in my viewpoint.

**Comment by abhinayagarwal** [comment]
It is not a workaround. The original used style is flawed. `.text` is the style-class for `LabeledText` which is a subclass of  `Text`. A Text can be colored using `-fx-fill` instead of `-fx-text-fill`.

We should either update:

```
.toggle-switch .text {
    -fx-font-size: 1em;
    -fx-text-fill: -fx-text-base-color;
}
```

to 

```
.toggle-switch .text {
    -fx-font-size: 1em;
    -fx-fill: -fx-text-base-color;
}
``` 

OR

```
.toggle-switch .label {
    -fx-font-size: 1em;
    -fx-text-fill: -fx-text-base-color;
}
```

I personally prefer the 2nd option. @Mason-Chou Since you reported this, would you like to raise a PR for the same?
