### ISSUE TITLE
module javafx.graphics does not "opens javafx.scene" to module org.controlsfx.controls

### ISSUE THREAD

**Issue by marvinjuette** [controlsfx/controlsfx#1148]
### Problem:
 If I create an Wizard (Code is available in attached files) I got the error message (also attached as .txt). I think it is an Problem with the Linear Flow, cause I this error also apperas when I add an empty second WizardPane (page2).

Hope you can help me.

Thanks Marvin.

[TemplatesWizard.txt](https://github.com/controlsfx/controlsfx/files/3124354/TemplatesWizard.txt)
[AmountPage.txt](https://github.com/controlsfx/controlsfx/files/3124356/AmountPage.txt)
[ClassificationPage.txt](https://github.com/controlsfx/controlsfx/files/3124357/ClassificationPage.txt)
[ErrorMessage.txt](https://github.com/controlsfx/controlsfx/files/3124358/ErrorMessage.txt)

**Comment by abhinayagarwal** [comment]
The error speaks for itself, you need to pass `--add-opens=javafx.graphics/javafx.scene=org.controlsfx.controls` as a runtime argument to the JVM.

**Comment by marvinjuette** [comment]
Ok thanks that works perfectly! 
But will the runtime argument be passed to packager when building a .jar file?

**Comment by abhinayagarwal** [comment]
You cannot pass the JVM argument directly to the jar. You need to pass it to the JVM. You can create a package of your application and set the runtime arguments in it.

**Comment by schelldorfer** [comment]
why do you not add line `opens org.controlsfx.controls to javafx.graphics` to module-info.java in your module org.controlsfx.controls?
