### ISSUE TITLE
NotificationPane depends on com.sun.* API and therefore isn't usable with OpenJFX 11

### ISSUE THREAD

**Issue by lestard** [controlsfx/controlsfx#1152]
The `NotificationPane` cannot be used with OpenJFX 11 and modules enabled because it depends on `com.sun.javafx.scene.traversal.ParentTraversalEngine`.

The error message is:

"
java.lang.IllegalAccessError: class impl.org.controlsfx.skin.NotificationPaneSkin (in module org.controlsfx.controls) cannot access class com.sun.javafx.scene.traversal.ParentTraversalEngine (in module javafx.graphics) because module javafx.graphics does not export com.sun.javafx.scene.traversal to module org.controlsfx.controls
"

**Comment by abhinayagarwal** [comment]
This is a known issue. In order to by pass it, you need to pass the following JVM argument while launching your project:

```
--add-exports=javafx.graphics/com.sun.javafx.scene=org.controlsfx.controls,
--add-exports=javafx.graphics/com.sun.javafx.scene.traversal=org.controlsfx.controls
```

**Comment by goxr3plus** [comment]
@abhinayagarwal  

Can you help me on this similar issue too ? What add export i have to add #1161
