### ISSUE TITLE
Please release like (v.v.v) like 11.0.0

### ISSUE THREAD

**Issue by goxr3plus** [controlsfx/controlsfx#1158]
It's not a good practise to use `v` or any letter in front of release because it breaks Java 9 auto module creation.

**Comment by abhinayagarwal** [comment]
Are you talking about the tags?

**Comment by goxr3plus** [comment]
Yes the extra v 'v11.0.0' is causing problems.

I found ControlsFX in Maven central where it is like '11.0.0' which is thr
correct.

**Comment by abhinayagarwal** [comment]
Can you please describe how is the tag name causing problem for auto module creation?

**Comment by abhinayagarwal** [comment]
Moreover, ControlsFX 11.0.0 is modularized.

**Comment by goxr3plus** [comment]
I will send you a link.

**Comment by abhinayagarwal** [comment]
@goxr3plus Can you confirm if there is still a problem?

**Comment by goxr3plus** [comment]
I think it's working okay i will close for now.
