### ISSUE TITLE
Features page linked from README.md is missing

### ISSUE THREAD

**Issue by jimmoores** [controlsfx/controlsfx#1159]
The separate features page linked to by the README.md file appears to be missing. I therefore can't see what features controls fx has!

**Comment by abhinayagarwal** [comment]
Feel free to create a PR

**Comment by jeacott1** [comment]
how would a controlsfx newbie create a features page? - the features page that is linked bounces back to to this github. nobody can see what controlsfx does.

**Comment by jimmoores** [comment]
I managed to miss the initial reply. I find it hilarious that I showed interest in this project, couldn't see what features it had, and rather than just clicking away, reported it, and was told to do it myself. Look, I maintain my own open source projects, I realise that I'm not entitled to support, but if anybody cares about bringing new users to this project at all, someone should fix  this, and I don't have the knowledge to do it.

**Comment by JonathanGiles** [comment]
The old features page is here: http://fxexperience.com/controlsfx/features/
If someone was kind enough to transfer this into GitHub, that would be great.

**Comment by jeacott1** [comment]
@JonathanGiles it seems someone has just now made that link accessible.
very helpful thanks.

**Comment by JonathanGiles** [comment]
Yes, me, for the purpose of having someone move it to GitHub - then I plan to take it back down. It is better in the centrally managed github repo rather than on my website.

**Comment by jeacott1** [comment]
if its your content isnt it easiest for you to copy it to the repo here rather than someone scraping it from the web?

**Comment by JonathanGiles** [comment]
I'm fine with it being scraped from the web. It's not more easy for me than anyone else.

**Comment by jeacott1** [comment]
you have all the images and whatever already in a folder. somewhere. pulling it from the web never works so cleanly,

**Comment by JonathanGiles** [comment]
They are all sitting on a web server I don't have file access to. I would need to pull them down from the web in the same way.

**Comment by jimmoores** [comment]
Now I have access to the source material, I will submit a PR.

**Comment by jimmoores** [comment]
#1173 has been submitted.

**Comment by abhinayagarwal** [comment]
Added the page to ControlsFX wiki.
