### ISSUE TITLE
Several Dialog classes missing JavaDocs

### ISSUE THREAD

**Issue by grimreaper** [controlsfx/controlsfx#1162]
The short description for several of the Dialog classes are missing. It is unclear what the CommandLinksDialog or ExceptionDialog do from reading the JavaDocs. In addition clicking into them show no additional explanation.

![image](https://user-images.githubusercontent.com/433817/58696266-14ba0800-834c-11e9-9891-36bd11fec31b.png)

ref #41

**Comment by abhinayagarwal** [comment]
@grimreaper Feel free to create a PR :)
