### ISSUE TITLE
Re-integrate TestFX tests in branch 9.0.0

### ISSUE THREAD

**Issue by danielpeintner** [controlsfx/controlsfx#1164]
[Original Searchable ComboBox PR](https://bitbucket.org/controlsfx/controlsfx/pull-requests/672/ff2a6b2c7e97/) had a few test written with TestFX. When ported to branch 9.0.0, it did not seem to work properly anymore (see https://github.com/controlsfx/controlsfx/pull/1154 for some details).

For the time being the tests have been removed (see [tests.zip](https://github.com/controlsfx/controlsfx/files/3255828/tests.zip)) and should be re-integrated once we know how to resolve these issues.

**Comment by abhinayagarwal** [comment]
`JavaFXThreadingRule.java` has also been removed since it had a dependency on `javafx-swing` module.

**Comment by abhinayagarwal** [comment]
Superseded by #1168
