### ISSUE TITLE
Features list doesn't work

### ISSUE THREAD

**Issue by davidfindlay** [controlsfx/controlsfx#1170]
On the Github Readme there's a link to the Features list, which doesn't actually work, just takes you to the main Github project page again.

**Comment by wirew0rm** [comment]
The original content from last October can be found in the wayback machine at [archive.org](https://web.archive.org/web/20181024133534/http://fxexperience.com/controlsfx/features). But even there it states, that this list is incomplete and the javadoc should be consulted for a complete list of all features. It also has images for all controls but there isn't a nice gallery view (at least none that I found).
Additionally i can recommend the sample application for checking out the features.

The dead link can also be found in the javadoc overview, and the issues link over there is also not working:
https://github.com/controlsfx/controlsfx/blob/c832f91b3d3685ced30ac5b1f5a2fe90204b4270/controlsfx/src/main/docs/overview.html#L11-L14

**Comment by abhinayagarwal** [comment]
@JonathanGiles Can you fix this?

**Comment by JonathanGiles** [comment]
It's here: http://fxexperience.com/controlsfx/features/
But I would love to see this in GitHub.

**Comment by danielpeintner** [comment]
I completely agree.

If I may make a proposal I think it would be best to setup `controlsfx.github.io` by creating such a repo (see https://pages.github.com/). 

Moreover, the link to http://docs.controlsfx.org/ in `README.md` which refers to https://controlsfx.bitbucket.io/ could be updated/hosted there also (documentation mentions "controlsfx 8.40.14 API" which is not up-to-date anymore)

**Comment by abhinayagarwal** [comment]
@danielpeintner Sounds like a good idea. For the time being everything is in the Wiki. First setup would be to create https://controlsfx.github.io/javadoc. I have created a separate repository under ControlsFX to host the Javadoc. A step could be added to the release pipeline to commit the updated Javadoc to this repository every time a release is being made.

ControlsFX 8 and 11 can have their own separate documentation as we have for [OpenJFX](https://github.com/openjfx/javadoc)

**Comment by danielpeintner** [comment]
I have seen the wiki with ControlsFX features. I am also fine keeping with keeping the wiki as is it but we might want to check the content again (e.g., dialogs are not anymore supported as described and the wiki points to the [old location](http://fxexperience.com/controlsfx/features/dialogs/)).

Separate repositories under ControlsFX to host the Javadoc make perfect sense to me.

FYI: I can help setting up github pages and provide a basic Yaml template as I did for another project a while ago (see https://github.com/EXIficient/exificient.github.io or [rendered version](http://exificient.github.io/java/))

**Comment by abhinayagarwal** [comment]
@danielpeintner Ah, I didn't update the dialog link in the readme. Thanks for reporting. I have fixed it.

We do not need a repository to host ControlsFX website for now. Just need an addition to commit javadoc files to controlsfx/javadoc repository on every release.

**Comment by abhinayagarwal** [comment]
Features are now listed as a part of [Wiki](https://github.com/controlsfx/controlsfx/wiki/ControlsFX-Features).

**Comment by danielpeintner** [comment]
One minor comment: I believe that [Dialogs](https://github.com/controlsfx/controlsfx/wiki/ControlsFX-Features#dialogs) have been removed....
