### ISSUE TITLE
ControlFx not compatible with JDK11 and JFX 11 when building in NB11

### ISSUE THREAD

**Issue by rsabhi** [controlsfx/controlsfx#1171]
I am trying to use controlsfx in NB11 with Jdk11. For the build I am using ivy.xml file and tried to use <dependency org="org.controlsfx" name="controlsfx" rev="11.0.0" /> But I am getting error as package not found for checkcombobox or none of the import package doesnt worked for me. Could you please provide me a suggestion on this?

Thanks,

**Comment by abhinayagarwal** [comment]
Hi @rsabhi,

Thank you for your patience. Just checking out if you have found a solution to the problem or still need our help?

**Comment by rsabhi** [comment]
@abhinayagarwal Thanks for reaching out, really appreciated. Yes its solved.
