### ISSUE TITLE
Many feature disappear in 11.0.0

### ISSUE THREAD

**Issue by kevin-lucifer** [controlsfx/controlsfx#1177]
Such as TextFields, SearchableComboBox. have been removed,  or replace by a new impl?

**Comment by abhinayagarwal** [comment]
Hi @kevin-lucifer,

All of the above said controls are available in ControlsFX 11.

**Comment by kevin-lucifer** [comment]
> Hi @kevin-lucifer,
> 
> All of the above said controls are available in ControlsFX 11.

Hi, thanks for your time. I can't find these in neither v11  release(https://repo.maven.apache.org/maven2/org/controlsfx/controlsfx/11.0.0/controlsfx-11.0.0.jar) nor v11.0.0 tag(cea2beb7). Could u please give me a code reference?
