### ISSUE TITLE
SpreadsheetCell missing in controlsfx-11.0.0.jar

### ISSUE THREAD

**Issue by danielvoinea** [controlsfx/controlsfx#1182]
Is it still supported SpreadsheetCell with java 11? 

These classes are missing in controlsfx-11.0.0.jar :
import org.controlsfx.control.spreadsheet.SpreadsheetCell;
import org.controlsfx.control.spreadsheet.SpreadsheetCell.CornerPosition;

**Comment by danielvoinea** [comment]
![SpreadsheetClassesMissing](https://user-images.githubusercontent.com/452721/65343006-ab048900-dbdc-11e9-9dc2-08d1875a6156.PNG)

**Comment by Maxoudela** [comment]
The SpreadsheetView is not (yet) in ControlsFX 11

**Comment by yuliu2016** [comment]
Is this being worked on somewhere right now or is it just a plan for the future?

**Comment by abhinayagarwal** [comment]
Duplicate of #1141
