### ISSUE TITLE
Typo in ControlsFX-Samples jvmArgs options

### ISSUE THREAD

**Issue by jperedadnr** [controlsfx/controlsfx#1189]
This applies to branch 9.0.0.

The [run task](https://github.com/controlsfx/controlsfx/blob/9.0.0/controlsfx-samples/build.gradle#L66) is overridden with these jvmArgs:

```
run {
    doFirst {
        java9Args.addAll(java9RuntimeArgs)
        jvmArgs = java9RuntimeArgs
    }
}
```

but it should be:
```
run {
    doFirst {
        java9Args.addAll(java9RuntimeArgs)
        jvmArgs = java9Args
    }
}
```

**Comment by Maxoudela** [comment]
Shouldn't this issue be closed?
