### ISSUE TITLE
CheckComboBox can be slow to display drop down

### ISSUE THREAD

**Issue by Arthurm1** [controlsfx/controlsfx#1203]
When there are a lot of items in the `CheckComboBox` control (e.g. 3000), it can be slow to open when clicked on.

This seems to be down to the `computePrefWidth` in `ComboBoxListViewSkin#createListView`.  It iterates through _all_ items and calculates their widths.

`ComboBox` gets round this performance hit with the undocumented
`COMBO_BOX_ROWS_TO_MEASURE_WIDTH_KEY = "comboBoxRowsToMeasureWidth"` in `ComboBoxListViewSkin` which is read from the `ComboBox#getProperties` and allows the user to limit the number of items in the list that are used e.g. first 20.

`CheckComboBoxSkin` does not apply properties from the `CheckComboBox` to the internal `ComboBox` when it creates it nor does it expose this `ComboBox` so it's not possible to set this property and bypass the performance hit.

Would it be possible to pass the `CheckComboBox` properties to the internal `ComboBox`?
Or to expose `rowsToMeasure` as a property on `CheckComboBox` which sets the underlying `ComboBox` property?

**Comment by Maxoudela** [comment]
Seems fair. You can provide a pull request if you want, that would be appreciated and could speed the process of resolving this :)

**Comment by Arthurm1** [comment]
A PR using the 2nd method - i.e. creating a property on `CheckComboBox`?

I'm not sure whether passing all the properties to the underlying `ComboBox` would cause other issues but the additional property would mean the interface would change on `CheckComboBox`

**Comment by Maxoudela** [comment]
I let you be the judge on the best solution but it's easier to discuss on an actual PR. Maybe begin simple with the rowsToMeasure property that will be set on the ComboBox? It should be simple and resolve your issue right?

**Comment by abhinayagarwal** [comment]
It is actually weird that `COMBO_BOX_ROWS_TO_MEASURE_WIDTH_KEY` is still a private field on the `ComboBoxListViewSkin` making this invisible for the general user.

I propose that we add a public static field to the `CheckComboBox` with some javadoc and then pass this to the internal ComboBox.
