### ISSUE TITLE
Javadocs Site for ControlsFX 11 API?

### ISSUE THREAD

**Issue by dlemmermann** [controlsfx/controlsfx#1204]
Do we already have a public site for the 11 modularized javadocs API for controlsfx? I am trying to link to it when generating the javadocs for FlexGanttFX.

**Comment by abhinayagarwal** [comment]
Not yet. Will release it soon.

**Comment by dlemmermann** [comment]
That would be awesome. My docs look stupid without those links to the ControlsFX controls that it uses.

Dirk

**Comment by abhinayagarwal** [comment]
Took me sometime. These are now available at: https://controlsfx.github.io/javadoc/11.0.1/index.html

**Comment by danielpeintner** [comment]
First of all thanks!

2 minor comments to the main javadoc page that could be fixed for the next version
* The features page points to the *old* http://fxexperience.com/controlsfx/features/ page
* Bug / Feature Tracker link is broken

Hope this helps

**Comment by abhinayagarwal** [comment]
@danielpeintner That's because the Javadocs is built from 11.0.1 tag. These are [fixed here](https://github.com/controlsfx/controlsfx/commit/5a38beb4348fa7359c6fb241f251a82243941bb1). Can you please check if anything else needs fixing?

**Comment by danielpeintner** [comment]
I see. Thanks. I did not find anything else.
