### ISSUE TITLE
A lot of old issues. Proposal

### ISSUE THREAD

**Issue by serieznyi** [controlsfx/controlsfx#1205]
Hello.
I see you have a lot old issues what trash yours space. 
Maybe you can use [Stale](https://github.com/marketplace/stale) bot;
He automatically close all abandoned issues in yours repository.
I seen how he worked in this [repository](https://github.com/Sylius/Sylius/issues?q=is%3Aissue+label%3AStale+is%3Aclosed)
[Example of config file](https://github.com/Sylius/Sylius/blob/master/.github/stale.yml)
In final you get only actual issues.

What you think about this?

**Comment by abhinayagarwal** [comment]
Sounds like a good idea.

@Maxoudela what do you think?

**Comment by Maxoudela** [comment]
Could be a good way to clean up a bit old issues. 
I see that bugs are for example discarded, this is good (I was afraid we could stale old bugs).

**Comment by serieznyi** [comment]
> Could be a good way to clean up a bit old issues.
> I see that bugs are for example discarded, this is good (I was afraid we could stale old bugs).

If you don`t fix old bugs through 5 years they not a critical.
Maybe later old bugs return as new )
