### ISSUE TITLE
ControlsFX features wiki partly out-dated

### ISSUE THREAD

**Issue by danielpeintner** [controlsfx/controlsfx#1209]
I noticed that the wiki about ControlsFX still mentions "Dialogs"
https://github.com/controlsfx/controlsfx/wiki/ControlsFX-Features#dialogs

I believe dialogs have been removed after JDK version 8u40 included dialogs.

Moreover, I think one can add more *features* such as e.g., 
* [SearchableComboBox](https://github.com/controlsfx/controlsfx/blob/master/controlsfx/src/main/java/org/controlsfx/control/SearchableComboBox.java)
* Anything else?

Is it ok if a provide a PR for it (https://github.com/controlsfx/controlsfx.wiki.git) or do you prefer updating it yourself?

**Comment by abhinayagarwal** [comment]
AFAIK, a contributor cannot create a PR to the wiki. If you can supply a diff, I will commit the changes.

**Comment by danielpeintner** [comment]
Attached a patch. Essentially I just removed dialogs and ActionTraits which does not exist anymore 
([dialogs-patch.txt](https://github.com/controlsfx/controlsfx/files/3819798/dialogs-patch.txt)).

For SearchableComboBox addition I propose the following text
"A SearchableComboBox is a simple extension of a ComboBox which shows a search field while the popup is showing. The user can type any text into this search field to filter the popup list."

A screenshot can be found here
https://github.com/controlsfx/controlsfx/blob/master/controlsfx/src/main/docs/org/controlsfx/control/searchable-combo-box-3.png

Feel free to change text or image.

**Comment by abhinayagarwal** [comment]
Updated!

**Comment by danielpeintner** [comment]
Thanks.

You seem to have missed to remove the *initial* navigation link to "Dialogs".
It is still there and points to nowhere. 

Hope this helps.
