### ISSUE TITLE
Wrap content in exception dialog

### ISSUE THREAD

**Issue by falkoschumann** [controlsfx/controlsfx#1211]
Without preferred width the content label will not wrap, only expand the dialog.

#1155 is incomplete see also DialogPane#createContentLabel(String)

Simple test:

    public static void main(String[] args) {
        new JFXPanel();

        Platform.runLater(() -> {
            Exception e = new IllegalStateException("Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.");
            ExceptionDialog dialog = new ExceptionDialog(e);
            dialog.showAndWait();
        });
    }

**Comment by Maxoudela** [comment]
Should we set an arbitrary prefWidth then? Do you have any clue on how to fix this?

**Comment by falkoschumann** [comment]
The content label is used when `DialogPane#contentText` is set, but `DialogPane#content` is not set. The content label is created in `DialogPane#createContentLabel` with this code:

        Label label = new Label(text);
        label.setMaxWidth(Double.MAX_VALUE);
        label.setMaxHeight(Double.MAX_VALUE);
        label.getStyleClass().add("content");
        label.setWrapText(true);
        label.setPrefWidth(360);
        return label;

Current code from `ExceptionDialog`:

    // --- content
    String contentText = getContentText();
    Label contentLabel = new Label(contentText != null && ! contentText.isEmpty() ? contentText : exception.getMessage());
    contentLabel.setWrapText(true);
    dialogPane.setContent(contentLabel);

I don't understand, why reading content text here. The code is taken from constructor, so content text can not be set at this point. Why creating a new label?

I would code this:

    // --- content
    setContentText(exception.getLocalizedMessage());

Also I use `exception.getLocalizedMessage()` instead of `exception.getMessage()`.

**Comment by Maxoudela** [comment]
Can you provide a PR so we can talk on it?
