### ISSUE TITLE
NPE from Notifications.show() if app has no window open

### ISSUE THREAD

**Issue by ChrisLMerrill** [controlsfx/controlsfx#1213]
If the app does not currently have a window open, this exception is thrown:

> Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
> 	at org.controlsfx.control.Notifications$NotificationPopupHandler.getScreenBounds(Notifications.java:364)
> 	at org.controlsfx.control.Notifications$NotificationPopupHandler.show(Notifications.java:343)
> 	at org.controlsfx.control.Notifications.show(Notifications.java:305)

If the app does have a window open, the problem does not occur.

In my case, the app is running in the background with only the SystemTray icon visible (AWT).

**Comment by Maxoudela** [comment]
Could you be more specific? You mean that you have not called "Stage.show()"?

**Comment by ChrisLMerrill** [comment]
I've called Stage.show(), but that stage has been closed. The app is still running in the background and another stage may be shown in the future....but when the notification needs to be shown, there may or may not be a Stage present.

**Comment by Maxoudela** [comment]
Allright. I think this should not be the only controlsfx to have issues if the Stage is not visible.

Can you provide a pull request fixing the issue?

**Comment by ekpeters** [comment]
If I'm reading between the lines properly, it looks like the autobuild of this failed for some reason?  I'm seeing basically  the same error and would be happier not hand-compiling fixes into external projects...

[2020-02-13 01:15:16] [build] [2020-02-13 01:15:16] [autobuild] * Exception is:
[2020-02-13 01:15:16] [build] [2020-02-13 01:15:16] [autobuild] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':controlsfx:compileJava'.

**Comment by JavaBloxx** [comment]
Whenever the window is minimized the notifications throw 

Exception in thread "JavaFX Application Thread" java.lang.NullPointerException: Owner window must not be null.

They start working again if the app window is up and visible on the screen. This issue didn't exist in controlsfx 8

**Comment by nicoi15** [comment]
Hi, any update on this? on version 11.0.2 I am receiving NPE whenever the window is minimized and the .show() is invoked.

java.lang.NullPointerException: Owner window must not be null
	at javafx.graphics/javafx.stage.PopupWindow.validateOwnerWindow(PopupWindow.java:931)
	at javafx.graphics/javafx.stage.PopupWindow.show(PopupWindow.java:434)

**Comment by nicolabeghin** [comment]
Any update on this?

**Comment by Maxoudela** [comment]
Hi guys,

Can somebody do a PR targeting jfx-13 in order to resolve this issue? That would be much appreciated. Otherwise I'll try to do it myself by I don't have much time right now 🤕

**Comment by Torrenal** [comment]
Can this please be pulled into a standard build?
I’m having to manually build this into a custom build of ControlsFX again, after having wrongly assumed you got this included after you solved whatever build issues you had back in March.

FWIW, my scenario is a FX window is open, but not focused, leading to a NPE when opening notifications (mixed Swing/FX UI).  This fix causes the open/unfocused window to be returned when no Fx window is focused, avoiding the NPE.

**Comment by falkoschumann** [comment]
I done a PR.

But while I test, I see a new problem. The notification is hidden by other windows. My test case is a Pomodoro timer. When the timer reached 0, the notification window opened behind the IDE window, if the Pomodoro app is not focused. Notifications use a popup window to showing the notification, but a popup window can not be modal like a stage. Any idea to solve this?
