### ISSUE TITLE
Build failure running gradlew run

### ISSUE THREAD

**Issue by antic-ml** [controlsfx/controlsfx#1218]
Here's the output from Gradle when I ran 'gradlew run':

C:\Users\Mario\Documents\GitHub>cd controlsfx

C:\Users\Mario\Documents\GitHub\controlsfx>gradlew run

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '13.0.1'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by abhinayagarwal** [comment]
If you want to build ControlsFX against Java 13+, you need to update Gradle wrapper version to 6+.

**Comment by Maxoudela** [comment]
@antic-ml Did upgrading gradle wrapper solved your problem? If so, you can close the issue
