### ISSUE TITLE
ListSelectionView empty targetItems

### ISSUE THREAD

**Issue by ugurkara** [controlsfx/controlsfx#1224]
Hi Everyone,

I'm using ListSelectionView. I added to targets a few items. The list view of target is showing the items I added.

But if I try to reach the list of the view, it show empty.

I'm using 11.0.0.

**Comment by abhinayagarwal** [comment]
Hi,

Can you please post an example to reproduce the issue?

**Comment by ugurkara** [comment]
Hi,

Create simple JavaFx Application and add following code to the start method;

        ListSelectionView<String> listView = new ListSelectionView<>();

        listView.getSourceItems().addAll("1", "2", "3", "4", "5");

        listView.getActions().add(new Action("Test", (ActionEvent arg0) -> {
            System.out.println("Target Item Size :" + listView.getTargetItems().size());
        }));

        Scene scene = new Scene(new StackPane(listView), 640, 480);
        
        stage.setScene(scene);
        stage.show();


select a item from source and add it to target and than click the test button.  It shows the list as empty.

**Comment by abhinayagarwal** [comment]
This seems to be a dup #1097. Can you check against the latest release v11.0.1?
