### ISSUE TITLE
NullPointerException in CheckComboBoxSkin.java:106

### ISSUE THREAD

**Issue by plantexchen** [controlsfx/controlsfx#1226]
Hi there,

we have a custom control based on CheckComboBox. After updating from ControlsFX 9 to 11.0.1 a NullPointerException occurs. Maybe someone can add an additional null check at the following position in **CheckComboBoxSkin.java:106**:

```
comboBox.setCellFactory(listView -> {
  CheckBoxListCell<T> result = new CheckBoxListCell<>(control::getItemBooleanProperty);
  result.focusedProperty().addListener((o, ov, nv) -> {
    if (nv) {
      result.getParent().requestFocus(); //result.getParent() is null!
    }
  });
  
  [...]
  
});
```

Greetings

**Comment by abhinayagarwal** [comment]
Dup #1219

**Comment by tanrikut** [comment]
Well resolution seems to be same with #1219 but here it is CheckComboBoxSkin class that still needs this null check.

**Comment by abhinayagarwal** [comment]
Hi @tanrikut,

Thank you for your comment. It makes to open this issue and fix it 👍
