### ISSUE TITLE
Make controls FXML-friendly via NamedArg annotation

### ISSUE THREAD

**Issue by hwaite** [controlsfx/controlsfx#1227]
Many ControlsFX widgets constructors are unavailable in FXML because constructors params are not named. Example: org.controlsfx.control.CheckComboBox(javafx.collections.ObservableList). Add javafx.beans.NamedArg annotations where appropriate. See also Issue https://github.com/controlsfx/controlsfx/issues/243.

**Comment by abhinayagarwal** [comment]
IMO, adding `@DefaultProperty` for a `ObservableList` property makes much more sense than `@NamedArg`.

**Comment by hwaite** [comment]
Are `@DefaultProperty` and `@NamedArg` mutually exclusive? I don't see an obvious reason _not_ to apply `@NamedArg` to every parameter of every public constructor for all controls. Would that make it more difficult for FXMLLoader to choose a ctor? Anyways, I'm fine with `@DefaultProperty` alone if that makes more sense.

**Comment by abhinayagarwal** [comment]
You can read more about these annotations [here](http://abhinay.xyz/javafx/2018/05/09/FXML-friendly-custom-controls.html).

For `ObservableList<S> items`, I personally feel that we should use `@DefaultProperty`.

**Comment by hwaite** [comment]
It sounds to me as if `@DefaultProperty` should be used whenever there's (1) a public, single-arg constructor and (2) no public constructors with more than one parameter. The vast majority of eligible ControlsFX components are lacking both annotations. Shall I just go ahead and update the lot of them?

**Comment by abhinayagarwal** [comment]
My preference is to use:

1. `@DefaultProperty` on controls which have a default (no-args) constructor
2. `@NamedArgs` in controls or classes which do not have a default (no-args) constructor

> Shall I just go ahead and update the lot of them?

Sure.

**Comment by hwaite** [comment]
I don't understand how existence of default ctor plays into the decision to use `@DefaultProperty`. I personally find it annoying when I'm unable to use a constructor in FXML just because its args aren't named. Since `@DefaultProperty` and `@NamedArg` can't coexist, I propose using the former only when doing so won't render some other public constructor inaccessible. This approach violates your preference in the case where there's a default ctor, a single-arg ctor *and* a multi-arg ctor.

I recognize that members can often be initialized via mutators rather than ctor args. As a best practice, I prefer the latter as it allows for better reasoning about state and assures that instance is not yet being observed. Is there any harm in blindly naming all contructor parameters for all ControlsFX classes (except for those that we decide need a `@DefaultProperty`)?

**Comment by wirew0rm** [comment]
@abhinayagarwal Is there any documentation about DefaultProperty and NamedArg being mutually exclusive? (I'm not really doubting it, in fact I have some code which tries to use both and I have always wondered what I am doing wrong.) Like @hwaite I cannot see the reasoning behind this design choice by javaFx and I wonder whether it might just be a bug/missing implementation branch in the FXML loader.

One thing to keep in mind is, that some controls might inherit the DefaultProperty annotation from their javafx superclass and at the same time add a non-default constructor, which would lead to another special case.

**Comment by abhinayagarwal** [comment]
> I recognize that members can often be initialized via mutators rather than ctor args. As a best practice, I prefer the latter as it allows for better reasoning about state and assures that instance is not yet being observed. Is there any harm in blindly naming all contructor parameters for all ControlsFX classes (except for those that we decide need a @DefaultProperty)?

@hwaite This is a valid point. But, adding `@NamedArgs` blindly on all parameters can often lead to some problems. For example, check this: https://stackoverflow.com/q/47025826/. In fact, I tried to cross check this and it fails in case of `CheckComboBox` as well.

```
<fx:define>
    <FXCollections fx:id="test" fx:factory="observableArrayList">
        <String fx:value="1" />
        <String fx:value="2" />
        <String fx:value="3" />
    </FXCollections>
</fx:define>
<CheckComboBox fx:id="ccb" items="${test}"/>
```

fails with `javafx.fxml.LoadException: Cannot bind to untyped object` if we the parameterized constructor has `@NamedArg` annotation.

where as, if you replace `CheckComboBox` with `ComboBox`, it just works. I need to dig deeper on what is causing this issue.

**Comment by abhinayagarwal** [comment]
> @abhinayagarwal Is there any documentation about DefaultProperty and NamedArg being mutually exclusive?

@wirew0rm Not that I am aware of.

> I wonder whether it might just be a bug/missing implementation branch in the FXML loader.

I better place to ask this question would be the JavaFX mailing list.

**Comment by Maxoudela** [comment]
Is PR #1228 ready to be merged or we have some doubts on the actual path we're on?

**Comment by abhinayagarwal** [comment]
@Maxoudela +1 for PR and since there is no more comments from anyone on this issue, close this too.
