### ISSUE TITLE
CheckComboBox.focusedProperty() listener is not available

### ISSUE THREAD

**Issue by Gunther10033** [controlsfx/controlsfx#1231]
I want add a change listener to  focusedProperty when the CheckComboBox get or lose the focus,but it can not work.
my code is following and it print nothing:

```
CheckComboBox_target.focusedProperty().addListener(new ChangeListener<Boolean>() {
    @Override
    public void changed(ObservableValue<? extends Boolean> observable, Boolean oldValue, Boolean newValue) {
        System.out.println("----------");
    }
});
```

**Comment by abhinayagarwal** [comment]
Please supply with a [SSCCE](http://www.sscce.org/).

**Comment by abhinayagarwal** [comment]
[HelloCheckComboBox](https://github.com/controlsfx/controlsfx/blob/master/controlsfx-samples/src/main/java/org/controlsfx/samples/checked/HelloCheckComboBox.java#L95) has a focus listener and it works just fine.
