### ISSUE TITLE
Caused by: java.lang.NoSuchMethodError: 'java.util.Iterator javafx.stage.Window.impl_getWindows()'

### ISSUE THREAD

**Issue by Swapnil722Git** [controlsfx/controlsfx#1233]
With OpenFX 11, OpenJDK 11 and controlsfx 8.40.15 library

Getting: 

     Caused by: java.lang.NoSuchMethodError: 'java.util.Iterator   javafx.stage.Window.impl_getWindows()' while execute following code.

    Notifications notifications = Notifications.create().title("Error").text("All fields are required.")
            .position(Pos.BOTTOM_CENTER);
    notifications.showConfirm(); //at this line geting error.  
When this issue will get fixed?

**Comment by danielpeintner** [comment]
You might want to use  v11.0.1.

There are different realeases for Java8 and Java9+.

Hope this helps

**Comment by Swapnil722Git** [comment]
Thanks It solved.

**Comment by Swapnil722Git** [comment]
> You might want to use v11.0.1.
> 
> There are different realeases for Java8 and Java9+.
> 
> Hope this helps
Thanks It solved.
