### ISSUE TITLE
PropertySheet providing invalid preferred height for branch 9.0.0?

### ISSUE THREAD

**Issue by danielpeintner** [controlsfx/controlsfx#1235]
I am converting a Java8 application to Java11. Doing so I noticed a difference with the PropertySheet control.

It looks like the property sheet provides an invalid preferred height information so that the layouting causes it to show vertical bars.

![ps-screenshot](https://user-images.githubusercontent.com/11281461/73162701-aef66980-40ee-11ea-8d6e-b9ed360cc73c.png)

To illustrate the issue I slightly updated the code in `HelloPropertySheet` by adding a button to show the property sheet in a dialog (see https://github.com/danielpeintner/controlsfx/commit/1384d78f3526250e403f6ffcec50cc339ca3753b)

Did anyone else notice this issue with property sheets?
Is it an issue of ControlsFX or JavaFX11+ ?

The same sample with Java8 does not show any scrollbars. 

Thanks for any hint and/or advice!

**Comment by abhinayagarwal** [comment]
Since ControlsFX 11 is just a fork out master (8), I highly doubt it has something to do with ControlsFX. Have you checked if the same can be reproduced without a Dialog?

**Comment by danielpeintner** [comment]
Unfortunately the issue seems to appear with `PropertySheet` only. Using a similar dialog with buttons does not cause vertical scrollbars (see https://github.com/danielpeintner/controlsfx/commit/8b5b54032d4384e7261d40c018c6e8511e7c1c40).

![no-scroll](https://user-images.githubusercontent.com/11281461/73939149-18ddf280-48e9-11ea-8b85-6efae9defeec.png)

There is no issue when `PropertSheet` is used in non dialog scenario at least in my use-cases...

**Comment by danielpeintner** [comment]
related to https://mail.openjdk.java.net/pipermail/openjfx-dev/2020-June/026818.html ?

**Comment by danielpeintner** [comment]
Fixed by https://github.com/openjdk/jfx/pull/336 ?

**Comment by abhinayagarwal** [comment]
@danielpeintner Have you got a chance to test the fix in the PR against `PropertySheet` ?

**Comment by danielpeintner** [comment]
Not yet. I might wait till an JavaFX early access build is available.
Will keep you informed...

**Comment by danielpeintner** [comment]
FYI: I gave JavaFX `16-ea+4` a try and the issue remains the same.
Maybe https://github.com/openjdk/jfx/pull/351 is yet another candidate to fix the problem...

**Comment by danielpeintner** [comment]
FYI: I just tried JavaFX `16-ea+5` and it seems to resolve the issue ...
