### ISSUE TITLE
Missing Import-Package information in MF file.

### ISSUE THREAD

**Issue by sdlzhd** [controlsfx/controlsfx#1237]
In the 5f887f1 submission, I found that the jar is missing the description of Import-Package in MF. 

But in the manifest block, there is still this description: `the manifest of the default jar is of type OsgiManifest`. The submission did not say why it was removed.

I am using the controlsfx bundle and this information is important to me. If Import-Package must be removed, I can only export this information myself, I don't think it is necessary.

These changes affected 8.40.16.

**Comment by Maxoudela** [comment]
Could you please provide a PR linked to this issue so we can directly on it? 
Don't forget to sign the CLA as mentioned in the contributing guidelines

**Comment by sdlzhd** [comment]
Glad to do it
