### ISSUE TITLE
GraphicDecoration: wrong placement for BOTTOM

### ISSUE THREAD

**Issue by xzel23** [controlsfx/controlsfx#1243]
The decoration's position is calculated in `GraphicDecoration.layoutGraphic()` with this code:

```
// y
switch (pos.getVpos()) {
    case CENTER: 
        y += targetHeight/2 - decorationNodeHeight / 2.0;
        break;
    case TOP: 
        y -= decorationNodeHeight / 2.0;
        break;
    case BOTTOM:
        y += targetHeight - decorationNodeWidth / 2.0;
        break;
    case BASELINE: 
        y += targetNode.getBaselineOffset() - decorationNode.getBaselineOffset() - decorationNodeHeight / 2.0;
        break;
}
```

Without trying it (I just saw it when browsing the code), I am pretty sure that for BOTTOM `decorationNodeWidth` should be replaced by `decorationNodeHeight` like this:

```
case BOTTOM:
    y += targetHeight - decorationNodeHeight / 2.0;
    break;
```

**Comment by abhinayagarwal** [comment]
Looks like a valid bug to me. Can you please test and create a PR?

**Comment by xzel23** [comment]
Ah, I'm sorry. I wanted to use the ControlsFX Decorations for my project, but ControlsFX pulled in too much JavaFX stuff (and more important the wrong version for my project, because I need JavaFX 14, and a patched fork of it that contains a bugfix critical for my project), so I created my own small Decoration class instead. But I looked at the ControlsFX code to see how it's done there and noticed this issue.

I don't have the time at the moment to create a test project and a PR. If I find some time later on, I can look into this again, but no promise when.

**Comment by dlemmermann** [comment]
I can definitely confirm this bug. I also had to fix it in my own Decoration class.

**Comment by Maxoudela** [comment]
Thanks for the bug report. I'll make the PR if you don't have time, no worry

**Comment by Maxoudela** [comment]
Can someone review?
