### ISSUE TITLE
Remove javafx.swing module

### ISSUE THREAD

**Issue by abhinayagarwal** [controlsfx/controlsfx#1252]
`javafx.swing` module is used by [JavaFXThreadingRule](https://github.com/controlsfx/controlsfx/blob/9.0.0/controlsfx/src/test/java/org/controlsfx/control/JavaFXThreadingRule.java). This class in turn is used by [CheckTreeViewTest](https://github.com/controlsfx/controlsfx/blob/9.0.0/controlsfx/src/test/java/org/controlsfx/control/CheckTreeViewTest.java).

IMO, it would be a good idea to get rid of both these classes and remove the dependency of ControlsFX on `javafx.swing`.

This will also provide us a **clean slate to introduce testing** for ControlsFX on 9.0.0 branch.

**Comment by abhinayagarwal** [comment]
@Maxoudela What's your take on this?

**Comment by Maxoudela** [comment]
It could be a good thing yes.

I known that I'm using [TestFX](https://github.com/TestFX/TestFX) in my project in order to do some tests that needs the UI. Maybe we could try to get rid of JavaFXThreadingRule and introduce testFX? I thought we already used it somewhere but I must be mistaken.

**Comment by abhinayagarwal** [comment]
We use TestFX to run some tests on **master** branch. I has removed it from **9.0.0** because I wasn't able to run them using JDK 11 and JPMS.

Nevertheless, I have [fixed it](https://github.com/controlsfx/controlsfx/commits/9.0.0) and brought back the tests which were based on TestFX.

Since my experience with TestFX is minimum, is it OK to assign the issue to you so that you can have a look at CheckTreeViewTest and do the needful? If not, I can have a look at TestFX later and fix it.

**Comment by Maxoudela** [comment]
Thanks, great!
Yes I've taken the issue and I will take a look on the test to switch it to testFX!

**Comment by abhinayagarwal** [comment]
Now that the JavaFXThreadingRule is fixed, I will assign the issue and take care of removing the `javafx.swing` module from the application. Thanks for your help @Maxoudela
