### ISSUE TITLE
Consider using CLA Assistant service

### ISSUE THREAD

**Issue by eugener** [controlsfx/controlsfx#1255]
Please check out https://cla-assistant.io/ which is capable of automatically checking/requiring CLA signing on GitHub.
@abhinayagarwal

**Comment by abhinayagarwal** [comment]
[ControlsFX CLA](https://cla.controlsfx.org) responses are stored in a Google Sheet instance. I have written a workflow which uses the existing infrastructure and queries Google Sheet responses to automate the CLA verification process.
