### ISSUE TITLE
Failing tests in headless mode

### ISSUE THREAD

**Issue by abhinayagarwal** [controlsfx/controlsfx#1258]
In headless mode, some tests start to fail. The interesting part is that these tests start to pass if I revert the change made to `SearchableComboBoxTest` in PR #1253 i.e. revert NUMPAD -> DIGIT. Not sure if this is a short coming of the monocle framework, TestFX or our tests :)

This issue is a blocker for PR #1257

![image](https://user-images.githubusercontent.com/3197675/79565132-af8b1480-80cd-11ea-9f20-364ef8a25738.png)

**Comment by Maxoudela** [comment]
Does this tests also fails with NUMPAD without headless mode?

Tests using digit are not working because my keyboard layout is in French ^^. I thought NUMPAD would be a convenient solution working for everybody. I'll investigate

**Comment by abhinayagarwal** [comment]
No, they don't fail when I am running tests with GUI.

**Comment by Maxoudela** [comment]
Allright, I can revert the `NUMPAD` to `DIGIT` and they will pass using headless mode no matter in what configuration the keyboard is. I don't have time right now to investigate why the NUMPAD is not working using headless mode.

I suggest that I revert this, and then we merge the headless test mode and everything will be settled.

**Comment by abhinayagarwal** [comment]
Sounds good to me. Thanks for taking the time to look into the issue.

**Comment by abhinayagarwal** [comment]
On a second thought, I can take care of reverting the change as a part of PR #1257
