### ISSUE TITLE
Importing ControlsFX to gradle with Java 11+

### ISSUE THREAD

**Issue by yovel123456** [controlsfx/controlsfx#1265]
Is there a proper tutorial of adding controlsfx to a Gradle project? What do I put in my build file and my module-info file to use the components and fxsampler?

**Comment by abhinayagarwal** [comment]
You can add ControlsFX as any other dependency. Is there a specific issue that you are facing?

**Comment by yovel123456** [comment]
No, I kinda got confused about adding the dependency to the build file and the module-info file. It is working now thanks.
