### ISSUE TITLE
RangeSlider still needs unexported com.sun.javafx.scene.control.behavior from javafx.controls module

### ISSUE THREAD

**Issue by MajeurAndroid** [controlsfx/controlsfx#1266]
Hi there,

I cannot manage to use RangeSlider in my project.

I know it was already an issue in 9.0.0 (See #1073), but I a am still facing this issue.

javafx-controls 14.0.1
controlsfx 11.0.1
openjdk version 14.0.1

`java.lang.IllegalAccessError: superclass access check failed: class impl.org.controlsfx.behavior.RangeSliderBehavior (in unnamed module @0x27a991d5) cannot access class com.sun.javafx.scene.control.behavior.BehaviorBase (in module javafx.controls) because module javafx.controls does not export com.sun.javafx.scene.control.behavior to unnamed module @0x27a991d5`

Any clue ?

**Comment by danielpeintner** [comment]
In https://github.com/danielpeintner/Java11Test/ I started once a Java11 test project with controlsfx.

In https://github.com/danielpeintner/Java11Test/blob/master/build.gradle#L118 you see for example what you need to open (it depends on the control you want to use)
e.g., 
`"--add-opens=javafx.controls/com.sun.javafx.scene.control.behavior=org.controlsfx.controls"`
OR
`"--add-opens=javafx.controls/com.sun.javafx.scene.control.behavior=ALL-UNNAMED"`

 Hope this helps.

**Comment by MajeurAndroid** [comment]
Thanks @danielpeintner ! This worked like a charm.

For those interested, in the maven openjfx plugin declaration:
```
<plugin>
    <groupId>org.openjfx</groupId>
    <artifactId>javafx-maven-plugin</artifactId>
    <version>0.0.4</version>
    <configuration>
        <options>
            <option>--add-opens</option>
            <option>javafx.controls/com.sun.javafx.scene.control.behavior=ALL-UNNAMED</option>
            <option>--add-opens</option>
            <option>javafx.controls/com.sun.javafx.scene.control.inputmap=ALL-UNNAMED</option>
            <option>--add-opens</option>
            <option>javafx.graphics/com.sun.javafx.scene.traversal=ALL-UNNAMED</option>
        </options>
        ...
    </configuration>
</plugin>
```

Don't no if I should close the issue, as long as it's kind of a workaround.

**Comment by abhinayagarwal** [comment]
These JVM flags will be required until we get rid of the Behavior classes :(

We are making progress and we have removed dependency on a [few of these flags](https://github.com/controlsfx/controlsfx/compare/b9a3b1e..48e7773#diff-c197962302397baf3a4cc36463dce5ea) since the last release.

**Comment by abhinayagarwal** [comment]
Dup #1073
