### ISSUE TITLE
Module not found: org.controlsfx.controls

### ISSUE THREAD

**Issue by ghostman2013** [controlsfx/controlsfx#1277]
I try to connect the library to my app and build it for **Mac OS** but I failed. Honestly, I am not sure if this error is related to **ControlsFX** but I don't know where I can ask yet. Unfortunately, I did not get any answer at [stackoverflow.com](https://stackoverflow.com/questions/61198633/error-module-not-found-org-controlsfx-controls).
Here is my **build.gradle**:
```
plugins {
    id 'application'
    id "org.beryx.jlink" version "2.17.5"
}

group 'com.contedevel'
version '1.0-SNAPSHOT'

application {
    mainClassName = 'com.contedevel.yummy.App'
    applicationName = 'yummy'
    applicationDefaultJvmArgs =  [
            "--add-opens=javafx.base/com.sun.javafx.runtime=org.controlsfx.controls",
            "--add-opens=javafx.base/com.sun.javafx.collections=org.controlsfx.controls",
            "--add-opens=javafx.graphics/com.sun.javafx.css=org.controlsfx.controls",
            "--add-opens=javafx.graphics/com.sun.javafx.scene=org.controlsfx.controls",
            "--add-opens=javafx.graphics/com.sun.javafx.scene.traversal=org.controlsfx.controls",
            "--add-opens=javafx.graphics/javafx.scene=org.controlsfx.controls",
            "--add-opens=javafx.controls/com.sun.javafx.scene.control=org.controlsfx.controls",
            "--add-opens=javafx.controls/com.sun.javafx.scene.control.behavior=org.controlsfx.controls",
            "--add-opens=javafx.controls/javafx.scene.control.skin=org.controlsfx.controls"
    ]
}

jlink {
    options = ['--strip-debug', '--compress', '2', '--no-header-files', '--no-man-pages']
    launcher {
        name = 'yummy'
    }
    jpackage {
        resourceDir = file("$buildDir/resources")
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation('org.controlsfx:controlsfx:11.0.1') {
        exclude group: 'org.openjfx'
    }
    compile 'org.webjars:font-awesome:5.13.0'
    testCompile 'junit:junit:4.12'
}
```

And **module-info.java**:  
```
module yummy {
    requires org.controlsfx.controls;
    requires javafx.controls;
    requires javafx.fxml;

    opens com.contedevel.yummy.gui to javafx.fxml;
    opens com.contedevel.yummy.control to javafx.fxml;
    exports com.contedevel.yummy;
}
```

And **IntelliJ IDEA** shows it can find the `org.controlsfx.controls` module, all is okey. But when I run `./gradlew run` I get the error:
```
module-info.java:2: error: module not found: org.controlsfx.controls
    requires org.controlsfx.controls;
```

Where can problem be at least?

**Comment by abhinayagarwal** [comment]
@ghostman2013 Welcome to ControlsFX!

Few things before we get into why it doesn't work:

1. By default Gradle will add all your dependencies to classpath.
2. To overcome this you need to use [Gradle Module plugin](https://github.com/java9-modularity/gradle-modules-plugin) or even better the [JavaFX Gradle plugin](https://github.com/openjfx/javafx-gradle-plugin/).
3. Where are your JavaFX dependencies?

**Comment by ghostman2013** [comment]
> @ghostman2013 Welcome to ControlsFX!
> 
> 
> 
> Few things before we get into why it doesn't work:
> 
> 
> 
> 1. By default Gradle will add all your dependencies to classpath.
> 
> 2. To overcome this you need to use [Gradle Module plugin](https://github.com/java9-modularity/gradle-modules-plugin) or even better the [JavaFX Gradle plugin](https://github.com/openjfx/javafx-gradle-plugin/).
> 
> 3. Where are your JavaFX dependencies?

I use **Liberica JDK** that includes JavaFX already. Thank you for answer, I will try this plugin when I will access to my laptop.

**Comment by abhinayagarwal** [comment]
No updates from OP
