### ISSUE TITLE
How to Limit CheckComboBox dropdown width

### ISSUE THREAD

**Issue by KenobySky** [controlsfx/controlsfx#1294]
Question

My dropdown list of the CheckComboBox expands to the size of the largest element entered in it, but I want to limit its width so it doesn't get larger than the screen width.

![Problem - unlimited width](https://user-images.githubusercontent.com/14953758/88585892-0fc51700-d02a-11ea-8dfb-af632a2f070f.png)

---------------------
| CheckComboBox | V |
--------------------------------------------
| "Long item 1 Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. (Out of screen bounds)|
--------------------------------------------
| "Long item 2"                              |
 --------------------------------------------
| "Long item 3"                              |
 --------------------------------------------

How do I fix this? How Do I limit the width to either the window width or the stage width or at least the screen width?

'CheckComboBox Dropdown' has the same width of the 'CheckComboBox'

---
Code bellow will reproduce the issue:

```
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.layout.Pane;
import javafx.stage.Stage;
import org.controlsfx.control.CheckComboBox;

public class Main2 extends Application {

    @Override
    public void start(Stage stage) {

        Pane root = new Pane();

        CheckComboBox<String> box = new CheckComboBox<>();
        double width = 200;
        box.setMinWidth(width);
        box.setPrefWidth(width);
        box.setMaxWidth(width);

        String item1 = new String("short name");
        String item2 = new String("Pellentesque habitant morbi tristique senectus et netus et " +
                "malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, " +
                "ultricies eget, tempor sit amet, ante.Pellentesque habitant morbi tristique senectus et netus et " +
                "malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, " +
                "ultricies eget, tempor sit amet, ante.");
        String item3 = new String("short name again");

        box.getItems().setAll(item1, item2, item3);
        root.getChildren().add(box);

        stage.setScene(new Scene(root, 300, 50));
        stage.show();
    }

    public static void main(String[] args) {
        launch();
    }
}
```

**Comment by abhinayagarwal** [comment]
Hi @KenobySky,

Thank you for this issue.

Can you check what happens in case of a normal ComboBox?

**Comment by abhinayagarwal** [comment]
This can be resolved by setting up a custom CellFactory and setting the text to a Label with `wrapText` property set to true.
