### ISSUE TITLE
controlsfx and javafx.controls dependencies both override javafx base

### ISSUE THREAD

**Issue by yovel123456** [controlsfx/controlsfx#1304]
When trying to use javafx 12+ ControlsFX override javafx.base version to 11.0.2 instead of 12+.
 Partial Solution: add javafx.base dependency (even though javafx.controls does that).

![image](https://user-images.githubusercontent.com/25065136/93487138-a4067880-f90d-11ea-82de-3d8747d17755.png)

Is there a diffrent/better solution?

**Comment by danielpeintner** [comment]
There used to be a related issue (which I cannot find at the moment).

I think the trick is to exclude javafx when adding the controlsfx dependency.

see for example in Gradle
```
dependencies {
    implementation ('org.controlsfx:controlsfx:11.0.2') {
        exclude group: 'org.openjfx', module: '*'
    }
   ...
```

**Comment by yovel123456** [comment]
Yes, I forgot about that. The answer for maven if anyone interested:
I will close the issue.

         <dependency>
            <groupId>org.controlsfx</groupId>
            <artifactId>controlsfx</artifactId>
            <version>11.0.2</version>
            <exclusions>
                <exclusion>  
                    <groupId>org.openjfx</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
