### ISSUE TITLE
Publishing 12 to Maven Central

### ISSUE THREAD

**Issue by luketn** [controlsfx/controlsfx#1308]
Hi, I am using the jfx-13 branch of the code for a project using JavaFX 14 and OpenJDK 14. 
To do so I've had to download the code, compile the branch and import as a local system dependency. 
Is there anywhere a maven repository I can use to fetch an early release of this branch (like a snapshot repository) that I could use?

**Comment by abhinayagarwal** [comment]
Hi @luketn ,

The jfx-13 branch hasn't been released yet. We are still deciding on what's a good way to release it. I am more inclined towards releasing ControlsFX `11.x.x-jfx13` instead of 13.0.0.

**Comment by luketn** [comment]
Thanks for letting me know. It'd be awesome to have the version released when you're ready. 
Throwing in my 2 cents: I prefer the 13.0.0 version number. It feels more logical to have the Major version of ControlsFX match the JavaFX version it is compatible with.

**Comment by danielpeintner** [comment]
> Throwing in my 2 cents: I prefer the 13.0.0 version number. It feels more logical to have the Major version of ControlsFX match the JavaFX version it is compatible with.

I tend to agree.
Having support for LTS versions like (8), 11, 17 and the *recent* JavaFX version like 15 makes most sense to me also.
