### ISSUE TITLE
ListSelectionView Button Graphics not Showing

### ISSUE THREAD

**Issue by jimTheRook** [controlsfx/controlsfx#1313]
I am working with ControlsFX (vs. 8.40.11) ListSelectionView and am having a problem getting the selection arrows to show. Originally they worked fine, but now I see the buttons but no arrows. Has anyone else experienced this problem or have any suggestions? Thanks for any help!

**Comment by abhinayagarwal** [comment]
Can you reproduce this issue using ControlsFX samples?

**Comment by jimTheRook** [comment]
It seems that the problem lies in the fact that the button graphics are provided by way of the internet. After digging into the source code for ListSelectionView I find that they are created by the following code:
FontAwesome fontAwesome = new FontAwesome();
        moveToTarget = new Button("",
                fontAwesome.create(FontAwesome.Glyph.ANGLE_RIGHT));

which creates a new Glyph by using a url;

public FontAwesome() {
        this("http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/fonts/fontawesome-webfont.ttf"); //$NON-NLS-1$
    }

The strange thing is that if I connect to a different internet connection, the graphics will sometimes show and sometimes will not.

**Comment by abhinayagarwal** [comment]
This issue was resolved long ago. Please use the latest version of ControlsFX 8.40.18.
