### ISSUE TITLE
Don't use Demos

### ISSUE THREAD

**Issue by Kscstg** [controlsfx/controlsfx#1315]
Hellow!
I can't use controlsfx demo, beacuse package(com.sun.javafx.scene.control.behavior.OrientedKeyBinding) don't exist in JDK11.

**Comment by Maxoudela** [comment]
Which version of ControlsFX are you using?

**Comment by Kscstg** [comment]
> 
> 
> Which version of ControlsFX are you using?

JDK11

**Comment by abhinayagarwal** [comment]
How are you running the samples?

**Comment by Kscstg** [comment]
> 
> 
> How are you running the samples?
Download controlsfx-master and run ControlsFXSample.java file.

**Comment by abhinayagarwal** [comment]
If you are cloning or downloading the repository as a zip, then you need to run the following from the root directory of the repository:

```
./gradlew run
```

**Comment by wirew0rm** [comment]
> > How are you running the samples?
>
> Download controlsfx-**master** and run ControlsFXSample.java file.

also you need to use the `9.0.0` branch, as the master branch expects JDK8 (which has javafx included in the JDK as opposed to later versions, where it is a separate dependency to openJFX).

**Comment by Kscstg** [comment]
Thank you. The problem has been solved
