### ISSUE TITLE
Hide element in gridview

### ISSUE THREAD

**Issue by lanthale** [controlsfx/controlsfx#1318]
I tried to hide an element in the gridview. Hiding is working but the space is left empty. 

Setting managed to false does not work to get a relayout of the gridview. The problem is that I cannot remove it from the list because from another thread I am iterating through the list. Therefore I have to find a way how I can hide an element from the grid.

My actual code to hide an element:

```
   @FXML
    private void stackButtonAction(ActionEvent event) {
        factory.getSelectedMediaItem().setVisible(false);
        factory.getSelectedMediaItem().setManaged(false);
        factory.getSelectedMediaItem().requestFocus();
        factory.getSelectedMediaItem().requestLayout();        
        factory.getSelectedCell().setVisible(false);        
        factory.getSelectedCell().setManaged(false);
        factory.getSelectedCell().requestLayout();                
        imageGrid.requestFocus();
        imageGrid.layout();
        imageGrid.requestLayout();
    }
```

**Comment by Maxoudela** [comment]
Hi,

Can you provide a simple code that we can actually copy/paste and run directly? 


We can literally do nothing with your code right now..

**Comment by lanthale** [comment]
Hi,

I have no found a workaround to for my issue because visually hide elements was not possible.
The workaround was to use filtertedLists for the grid view and hide the elements via filtering of the data.

The final code is in the following project https://github.com/lanthale/PhotoSlide/tree/master/PhotoSlide/src/main/java/org/photoslide/lighttable
