### ISSUE TITLE
HyperlinkLabel does not regain it's color after being clicked

### ISSUE THREAD

**Issue by aron-hoogeveen** [controlsfx/controlsfx#1322]
The color of the `HyperlinkLabel` is by default blueish. When it gets focus it keeps this color and gets underlined. But whenever you click on the button (or use space/enter when focused) the color becomes black. 

Versions used:
```
<dependency>
    <groupId>org.openjfx</groupId>
    <artifactId>javafx-controls</artifactId>
    <version>15.0.1</version>
</dependency>
<!-- https://mvnrepository.com/artifact/org.controlsfx/controlsfx -->
<dependency>
    <groupId>org.controlsfx</groupId>
    <artifactId>controlsfx</artifactId>
    <version>11.0.3</version>
</dependency>
```

**Comment by abhinayagarwal** [comment]
Hi @aron-hoogeveen ,

Thank you for filing the issue. Can you also add a [SSCCE](http://sscce.org/) which can easily reproduce the bug?

**Comment by aron-hoogeveen** [comment]
``` java
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.layout.BorderPane;
import javafx.stage.Stage;
import org.controlsfx.control.*;


/**
 * JavaFX App
 */
public class App extends Application {

    @Override
    public void start(Stage stage) {
        HyperlinkLabel hyperlinkLabel = new HyperlinkLabel("[Link] text");
        BorderPane root = new BorderPane();
        root.setCenter(hyperlinkLabel);

        stage.setScene(new Scene(root));
        stage.show();
    }

    public static void main(String[] args) {
        launch();
    }

}
```

Run the Application class (I used maven for getting the dependencies as stated in my first comment) and click on the link. Note that the link gets a black fontFill after being clicked.

**Comment by abhinayagarwal** [comment]
The control itself is not responsible for the color. The control just uses a `Hyperlink` and the color black comes from it.

Therefore, this is not an issue.

If you have any further questions, feel free to comment on the issue.
