### ISSUE TITLE
GridCell uses protected methods from VirtualFlow

### ISSUE THREAD

**Issue by abhinayagarwal** [controlsfx/controlsfx#1332]
`GridViewSkin` needs to access VirtualFlow#rebuildCells and VirtualFlow#reconfigureCells, which are protected methods and not accessible to GridViewSkin.

We need to dig and find out if these two calls are still necessary for the GridView to work. The code is a bit old so maybe it's not useful anymore.

If it's still useful, an approach similar to spreadsheet's GridViewSkin can be taken in GridView i.e. override the `createVirtualFlow()` method in order to provide a custom VirtualFlow that would either open these two methods, or help accessing them.

**Comment by Hugolarson** [comment]
Want to highlight that this issue is a showstopper for using ControlsFX with FX 15.
