### ISSUE TITLE
What happened to cross-platform dialogs?

### ISSUE THREAD

**Issue by UltraBurstXD** [controlsfx/controlsfx#1336]

**Comment by dlemmermann** [comment]
The dialogs API made it into the official JavaFX API.

**Comment by UltraBurstXD** [comment]
Well, that is new! But I can't find the cross-platform dialog code. Was it discontinued?

**Comment by dlemmermann** [comment]
Yes, AFAIK.

**Comment by eugener** [comment]
That happened 5-6 years ago :) 
Related ControlsFX code was removed once it became an official API. 
Few specialized dialogs are still part of the library. 
The code can be found at https://github.com/controlsfx/controlsfx/tree/jfx-13/controlsfx/src/main/java/org/controlsfx/dialog

**Comment by UltraBurstXD** [comment]
Ugh...! I was going to try emulate that for my custom stage.
