### ISSUE TITLE
Adjusting the padding of a checkbox's graphic within a CheckTreeView

### ISSUE THREAD

**Issue by m0squito** [controlsfx/controlsfx#1337]
I am using the CheckTreeView with FontAwesome5 via [FontIcon](https://kordamp.org/ikonli/#_fontawesome5_latest) as the graphic for each item. There is no padding on the left as shown below:
![Screen Shot 2021-02-04 at 11 33 52 AM](https://user-images.githubusercontent.com/1518512/106924213-dd812a00-66dc-11eb-9e7f-bcd760ce79ae.png)

Is there any way to adjust the padding of the checkbox so that there is some extra space between the box and the graphic? I've tried to adjust the padding of the icon, but to no avail.

I would appreciate any pointers, apologies if this belongs in StackOverflow!

**Comment by sovap** [comment]
you can wrap the node into hbox and handle the padding there
something like this:

ImageView imgViewDir = createImageView(dirImage);
                HBox imgHbox = new HBox();
                imgHbox.setAlignment(Pos.CENTER);
                imgHbox.setPadding(new Insets(0, 0, 0, 5));
                imgHbox.getChildren().add(imgViewDir);

CheckBoxTreeItem<GherkinTreeItem> newDirParent = new CheckBoxTreeItem<>(dirTreeItem, imgHbox);
