### ISSUE TITLE
how can set property-sheet -fx-background-color?

### ISSUE THREAD

**Issue by qq1053831109** [controlsfx/controlsfx#1339]
how can set property-sheet -fx-background-color?

**Comment by Maxoudela** [comment]
Could you be a bit more specific?

Here are the selectors you may be looking for:
`.property-sheet .scroll-pane .property-pane {
    -fx-background-color: red;
}

.property-sheet .scroll-pane {
    -fx-background-color: red;
    -fx-background-insets: 0;
    -fx-padding: 0;
}

.property-sheet .scroll-pane .accordion {
    -fx-padding: -1;
}`

![image](https://user-images.githubusercontent.com/8961645/120305107-af010d80-c2d0-11eb-96db-f2fb81325538.png)

**Comment by Maxoudela** [comment]
No response, does not seem like a bug.
