### ISSUE TITLE
Any equivalent of groupbox?

### ISSUE THREAD

**Issue by UltraBurstXD** [controlsfx/controlsfx#1340]
Hi, 
I came from C# and HMTL5 background and I used GroupBox and Fieldset a lot on my daily basis. So having built-in GroupBox equivalent on JavaFX would complete the wonderful controls sets we have already. I think even Swing has something similar (Forgotten the name^^). I think I'm not the only one feeling the same. Modifying big classes and create custom controls is not time saving...

**Comment by abhinayagarwal** [comment]
Hi @UltraBurstXD ,

Sorry, I am not accustomed to GroupBox. If you can throw some light on how it is different from what's already available in JavaFX, we could most probably build a control and add it to existing controls.

**Comment by UltraBurstXD** [comment]
Well from what I could see based on some researches, I found that we could add [titled border](https://stackoverflow.com/questions/46717684/gridpane-with-titled-border) to existing layout manager... But, that way isn't very desirable in most situations, e.g, if I would have to nest many layouts containers and have boilerplate of code to achieve something like this:

![TWuND](https://user-images.githubusercontent.com/55871338/107819916-99e48b00-6d82-11eb-9f4a-233d2871b545.png)

I wouldn't achieve nearly nothing but play with scene for many days...

**Comment by eugener** [comment]
I think that standard `TitledPane` is pretty close to want you'd like to achieve.
Form like layout can also be done using some of the existing JavaFX layouts such as `VBox` or `GridPane`
This is what `PropertySheet` control actually does

![image](https://user-images.githubusercontent.com/341840/107836904-ca212f00-6d6c-11eb-81d7-90b01b6ec37d.png)

**Comment by UltraBurstXD** [comment]
Even so, I don't have many customizing options and I would be obliged to nest many layouts containers to achieve something shown above. Maybe absolute positioning would be easy, but what about relative? And GroupBox isn't used only in forms, I have seen it in many kind of software. QT framework also offers it...

**Comment by eugener** [comment]
Of course, you can create a new control by combining above suggestions. Absolute positioning is almost never a good idea though. As for the way `TitledPane` looks, in JavaFX everything can be fully restyled using CSS to your liking.

**Comment by UltraBurstXD** [comment]
Alright, I'll try to customize `TitledPane` to look more like `GroupBox`.
