### ISSUE TITLE
Module javafx.graphics does not "opens javafx.scene" to unnamed module

### ISSUE THREAD

**Issue by BowgartField** [controlsfx/controlsfx#1346]
Hi,
I'm using:
- ControlsFX v11.1.0
- JavaFX 14 (added with maven)
- Maven 

and got this error when i'm trying validation on TextField.

`Exception in thread "JavaFX Application Thread "java.lang.reflect.InaccessibleObjectException: Unable to make protected javafx.collections.ObservableList javafx.scene.Parent.getChildren() accessible: module javafx.graphics does not "opens javafx.scene" to unnamed module @5b7e1162`

I have tried to export module but this didn't work:
`--add-opens=javafx.controls/javafx.scene.control.skin=org.controlsfx.controls`
got "WARNING: Unknown module: javafx.controls specified to --add-opens" error.

Thank for help.

**Comment by abhinayagarwal** [comment]
Hi,

From the exception, it is obvious that:

1. ControlsFX is added to classpath instead of module-path
2. It needs you to open `javafx.scene` package from `javafx.graphics` module.

Therefore, you need to do the following:

```
--add-opens=javafx.graphics/javafx.scene=ALL-UNNAMED
```

**Comment by BowgartField** [comment]
> Hi,
> 
> From the exception, it is obvious that:
> 
> 1. ControlsFX is added to classpath instead of module-path
> 2. It needs you to open `javafx.scene` package from `javafx.graphics` module.
> 
> Therefore, you need to do the following:
> 
> ```
> --add-opens=javafx.graphics/javafx.scene=ALL-UNNAMED
> ```

Hi,
Thanks for reply. I tried what you said but it's don't works.
So i thinks i'm doing something wrong.
I'm adding the arg like this:
`

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <release>14</release>

                    <compilerArgs>
                        <arg>
                            --add-opens=javafx.graphics/javafx.scene=ALL-UNNAMED
                        </arg>
                    </compilerArgs>

                </configuration>
            </plugin>
`

And the full error is:
`Exception in thread "JavaFX Application Thread" java.lang.reflect.InaccessibleObjectException: Unable to make protected javafx.collections.ObservableList javafx.scene.Parent.getChildren() accessible: module javafx.graphics does not "opens javafx.scene" to unnamed module @5b7e1162`. 
Thanks !

**Comment by abhinayagarwal** [comment]
Assuming, you are using `javafx-maven-plugin`, you also need to pass it to the argument to the same as well.

**Comment by BowgartField** [comment]
> Assuming, you are using `javafx-maven-plugin`, you also need to pass it to the argument to the same as well.

That's now working ! Thanks you very much.

Fot those who will get the same error i add this in the plugin "javafx-maven-plugin" section of pom file:
`<options>
        <option>--add-opens=javafx.graphics/javafx.scene=ALL-UNNAMED</option>
</options>`

In <configuration>
