### ISSUE TITLE
ToggleSwitch should impelment #onAction

### ISSUE THREAD

**Issue by mdindoffer** [controlsfx/controlsfx#1353]
ToggleSwitch should implement the `#onAction` (or #onSelection ?) property to enable full FXML declaration and binding to a Controller method.

Currently, when using FXML

```fxml
<ToggleSwitch fx:id="toggleSwitch" text="Caption"/>
```

, one must bind the control via `initialize()` in a Controller:
```java
@FXML
private void initialize() {
  toggleSwitch.selectedProperty().addListener((observable, oldValue, newValue) -> {
    if (newValue) {
      // do stuff
    } else {
      // do other stuff
    }
  });
}
```

This is cumbersome and makes it stand out from the rest of the controls such as a regular `Button`.

**Comment by abhinayagarwal** [comment]
I am not the original author of the control but I guess the reasoning behind this behaviour is `ToggleSwitch`, unlike `Button`, will have different actions for ON/OFF state.

If @dukke can comment on this, it would be great.

**Comment by dukke** [comment]
Hi,

It's been a good amount of years since I submitted ToggleSwitch to ControlsFX. In retrospect, for the sake of coherence, given that CheckBox (which is kind of similar to ToggleSwitch) extends from ButtonBase and so inherits an onAction event, maybe ToggleSwitch should have also extended from ButtonBase (and in that case also inherit an onAction event).

Meanwhile, if you want a similar solution to using onAction, you can use onMousePressed event of ToggleSwitch in FXML.

**Comment by mdindoffer** [comment]
So I think we agree. For me the `CheckBox`, JavaFX's `ToggleButton` and `ToggleSwitch` are conceptually *almost* the same thing, just with different visuals. Both the `CheckBox` and `ToggleButton` are based on `ButtonBase`.

@dukke Thanks for the tip for `onMousePressed`!

I'm not sure if this change can be done in a backwards-compatible way, so if it sounds like too much of an effort, I'm fine with the `onMousePressed` workaround.

**Comment by abhinayagarwal** [comment]
@dukke Thanks for the feedback!

@mdindoffer  `ToggleButton` can easily extend `ButtonBase` without breaking any backwards-compatibility. This will only add the API from `ButtonBase` in the control. If this is something that seems logical, we can always do it.

As of now a workaround exists for the issue reported by OP. Therefore, I am going to close this issue.

**Comment by dukke** [comment]
Your welcome @abhinayagarwal 🙂
