### ISSUE TITLE
Be compatible with Java 16

### ISSUE THREAD

**Issue by Maxoudela** [controlsfx/controlsfx#1370]
I encountered several issues when trying to build ControlsFX using OpenJDK 16 and OpenJFX 16. Mainly because OpenJDK 16 has an issue with the gradle version we are using, and if I upgraded Gradle, I had issues with the gradle script itself.

I will let my investigation here in case anyone has the same issue, and that it might be useful in the future. I'm planning on migrating my enterprise application from Java 8 to Java 17 therefore using ControlsFX.

-  Building with OpenJDK 16 using gradle wrapper (6.0.1) throws this exception:
```
Could not open cp_init remapped class cache for 86qn5sz6lnn8dinx4xyta0vad (C:\Users\\.gradle\caches\6.0.1\scripts-remapped\nb_tooling_6ukhmbjlntsqsc0ggimovv2f\86qn5sz6lnn8dinx4xyta0vad\cp_init27b7120d8bed45e60dd0b95b8e5ecea0).
> Could not open cp_init generic class cache for initialization script 'C:\Program Files\NetBeans-12.3\netbeans\extide\modules\gradle\nb-tooling.gradle' (C:\Users\\.gradle\caches\6.0.1\scripts\86qn5sz6lnn8dinx4xyta0vad\cp_init\cp_init27b7120d8bed45e60dd0b95b8e5ecea0).
   > Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7
```
It seems to be linked to the version of Gradle : https://stackoverflow.com/questions/61289461/java-lang-noclassdeffounderror-could-not-initialize-class-org-codehaus-groovy-v

- Upgrading the Gradle version to **6.8.2** for example, now triggers this exception:
```
Execution failed for task ':controlsfx:jar'.
> java.util.ConcurrentModificationException (no error message)
```
Somehow, the issue could be caused by the version of **biz.aQute.bnd.builder** (see https://github.com/gradle/gradle/issues/13628#issuecomment-672541910) so I've pushed this from **5.0.0** to **5.1.2**.

- But now I have 
```
Execution failed for task ':controlsfx:javadoc'.
> class java.lang.String cannot be cast to class java.util.List (java.lang.String and java.util.List are in module java.base of loader 'bootstrap')
```
I did not know what to do with that, so I simply remove the **javadoc** commands in the gradle scripts. Without that, it successfully builds.

- Pushing to Gradle **7.0.2** triggers these exception:
```
> Plugin with id 'maven' not found.
```
```
A problem occurred evaluating project ':controlsfx'.
> Could not find method testCompile() for arguments [junit:junit:[4,)] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```

Linked to #1287

**Comment by danielpeintner** [comment]
w.r.t. to `testCompile` I believe one should use `testImplementation` nowadays...
not sure if that resolves the issue though

**Comment by abhinayagarwal** [comment]
I can have a look at this sometime later this week, unless someone beats me to it ;)

**Comment by Maxoudela** [comment]
I just went crazy trying to debug an issue. I tried IntelliJ and Netbeans, but both are completely unable to make it work.
I'm stuck where I'm running it with JDK 16 but somehow I cannot add the JavaFX sources, therefore being go deep in the code.

So I just copied the whole sources and pasted them into a new Maven project. In 2 minutes I was debugging properly..

**Comment by abhinayagarwal** [comment]
Wow Gradle is a mess. I have wasted more than a few hours figuring things out and it seems that Gradle is performing some magic which is causing `controlsfx-samples` to fail as an application. I crossed check the `java` command and it seems fine.

With Gradle 7.x, JPMS support is auto enabled if a `module-info.java` is found in a project. This causing builds to fail.

I tried to switch it off using without any success:

```
java {
    modularity.inferModulePath = false
}
```

The other problem with our setup is that mainclass is present in `org.controlsfx.fxsampler` module and not in org.controlsfx.samples`. However, Gradle doesn't respect its own configuration. Using

```
application {
    mainModule.set('org.controlsfx.fxsampler')
    mainClass.set('fxsampler.FXSampler')
}
```

the Java command executed while running `gradlew run` is:

```
java ... --module org.controlsfx.samples/fxsampler.FXSampler
```

I tried to manually copy the java command and change the module, however, I kept getting:

```
> Task :controlsfx-samples:run FAILED
Error occurred during initialization of boot layer
java.lang.module.FindException: Error reading module: controlsfx/controlsfx-samples/build/classes/java/main
Caused by: java.lang.module.InvalidModuleDescriptorException: Package fxsampler not found in module
```

This issue doesn't just occur with Gradle 7. Try updating to Gradle 6.4 breaks the entire build. Gradle 6.4 doesn't enable JPMS automatically and is only supposed to have on-demand support for JPMS.

**Comment by Maxoudela** [comment]
Thanks for the investigation. What version of Gradle are we using right now? 
I never took the time to understand properly Gradle, therefore I won't be able to help much 😿 but I'll try to debug a bit on my side also

**Comment by abhinayagarwal** [comment]
ControlsFX is currently on Gradle 6.0.1: https://github.com/controlsfx/controlsfx/blob/jfx-13/gradle/wrapper/gradle-wrapper.properties#L6

**Comment by Yuanuo** [comment]
I've upgraded to Java17 & JavaFX17!

Just replace the build system from Gradle to Maven!! Maven is really easy!

You can look at the PR https://github.com/controlsfx/controlsfx/pull/1393 I pushed.

**Comment by JJBRT** [comment]
Please take a look at my new article that explain [how to export all modules to all modules at runtime in Java 16 and later](https://dev.to/jjbrt/how-to-avoid-resorting-to-add-exports-and-add-opens-in-jdk-16-and-later-j3m) without using any JVM parameter
