### ISSUE TITLE
how to write css code for spreadsheet

### ISSUE THREAD

**Issue by HamidShaikh1499** [controlsfx/controlsfx#1380]
I want to apply css on spreadsheetview. spreadsheetview is cool tool to use, but i didn't find about css how to apply
i want to change the color of selected cell of spreadsheet using  **programmatically** or using **css**.

please give some code to perform above task and please provide css also for spreadsheetview

**Comment by Maxoudela** [comment]
Hi,

You can take a look here at the examples: https://github.com/controlsfx/controlsfx/blob/jfx-13/controlsfx-samples/src/main/resources/org/controlsfx/samples/spreadsheetSample.css

Basically, in CSS, you can add the `:selected` property in your css. 

Could you elaborate on your specific need? If you need to change the color at runtime, one solution could be to register a custom css stylesheet to the scene at that moment. 
If you need to change the color during the lifetime of the SpreadsheetView itself, you can either use the `setStyle` method available on SpreadsheetCell, or modify their `styleClass` of you have programed the color before and simply need to change the color during the runtime.

**Comment by HamidShaikh1499** [comment]
@Maxoudela thanks for i will your link and manage it in runtime. JAVAFX
