### ISSUE TITLE
JFXCentral Entry

### ISSUE THREAD

**Issue by dlemmermann** [controlsfx/controlsfx#1386]
Would be great if this library could be added to JFXCentral at jfx-central.com. Data needs to be added to the data repository: https://github.com/dlemmermann/jfxcentral-data

**Comment by abhinayagarwal** [comment]
The entry is already here:https://github.com/dlemmermann/jfxcentral-data/blob/staging/libraries/libraries.json#L482

Let me know if something else needs to be done.

**Comment by dlemmermann** [comment]
Yeah, no idea why I added this issue. I actually think I created the entry myself, didn't I? :-)
