### ISSUE TITLE
JDK 17 forbids access to internal com.sun packages

### ISSUE THREAD

**Issue by DaveJarvis** [controlsfx/controlsfx#1394]
In `ReflectionUtils`, the following method violates the new security model in JDK 17:

    public static void setTraversalEngine(Control control, Object engine) {
        try {
            Class<?> parentHelper = Class.forName("com.sun.javafx.scene.ParentHelper");
            Method method = parentHelper.getMethod("setTraversalEngine", Parent.class, engine.getClass());
            method.setAccessible(true);
            method.invoke(parentHelper, control, engine);
        } catch (IllegalAccessException | InvocationTargetException | NoSuchMethodException | ClassNotFoundException e) {
            throw new RuntimeException("Cannot set Traversal Engine");
        }
    }

This prevents migration to JDK 17 for any JavaFX applications that use ControlsFX directly or indirectly (e.g., PreferencesFX).

FWIW, adding the export for scene traversal does not appear to resolve the issue:

```
def moduleSecurity = [
    "--add-opens=javafx.controls/javafx.scene.control=ALL-UNNAMED",
    "--add-opens=javafx.controls/javafx.scene.control.skin=ALL-UNNAMED",
    "--add-opens=javafx.graphics/javafx.scene.text=ALL-UNNAMED",
    "--add-opens=javafx.graphics/com.sun.javafx.css=ALL-UNNAMED",
    "--add-opens=javafx.graphics/com.sun.javafx.text=ALL-UNNAMED",
    "--add-exports=javafx.base/com.sun.javafx.event=ALL-UNNAMED",
    "--add-exports=javafx.graphics/com.sun.javafx.application=ALL-UNNAMED",
    "--add-exports=javafx.graphics/com.sun.javafx.geom=ALL-UNNAMED",
    "--add-exports=javafx.graphics/com.sun.javafx.scene.traversal=ALL-UNNAMED",
    "--add-exports=javafx.graphics/com.sun.javafx.text=ALL-UNNAMED",
]
```

**Comment by DaveJarvis** [comment]
Another developer provided the following options:

```

java -cp 'my-app.jar:/lib/*' \
 --module-path /Library/Java/JavaVirtualMachines/javafx-sdk-17/lib \
 --add-modules javafx.swing,javafx.controls,javafx.fxml,javafx.media,javafx.web,javafx.base,javafx.graphics \
 --add-exports=javafx.graphics/com.sun.javafx.scene=org.controlsfx.controls \
 --add-exports=javafx.graphics/com.sun.javafx.scene.traversal=org.controlsfx.controls \
 --add-exports=javafx.controls/com.sun.javafx.scene.control.behavior=org.controlsfx.controls \
 --add-exports=javafx.controls/com.sun.javafx.scene.control=org.controlsfx.controls \
 --add-exports=javafx.controls/com.sun.javafx.scene.control.inputmap=org.controlsfx.controls \
 --add-exports=javafx.base/com.sun.javafx.event=org.controlsfx.controls \
 --add-exports=javafx.base/com.sun.javafx.collections=org.controlsfx.controls \
 --add-exports=javafx.base/com.sun.javafx.runtime=org.controlsfx.controls \
 --add-exports=javafx.graphics/com.sun.javafx.scene.traversal=ALL-UNNAMED \
 --add-exports=javafx.graphics/com.sun.javafx.scene=ALL-UNNAMED \
 --add-exports=javafx.base/com.sun.javafx.event=ALL-UNNAMED \
 --add-opens=javafx.controls/javafx.scene.control.skin=org.controlsfx.controls \
 --add-opens=javafx.graphics/javafx.scene=org.controlsfx.controls \
 myClass
```

He said that those allowed his application to run with JDK 17.

**Comment by DaveJarvis** [comment]
It is unfortunate that the `module-path` is required:

     --module-path /Library/Java/JavaVirtualMachines/javafx-sdk-17/lib \

On my development machine the path is `/opt/jdk/lib`. Depending on where the user installs the Liberica JDK, the path will differ. This leads to a number of issues:

* What OS is the user running?
* What CPU architecture?

The only way to guarantee the location of the JavaFX module is to then include it in the JAR file. Wouldn't this mean bundling all versions of JavaFX for all platforms within an uberjar to make sure the program will run?

**Comment by DaveJarvis** [comment]
@abhinayagarwal 

> I created a draft PR #1395 to remove usages for ParentTraversal and Behavior calsses. You can try it out and see if it fixes the issue for you.

Are there any build instructions showing required versions of the requisite build tools (JDK, Gradle, Maven, etc.)?

``` bash
$ git clone https://github.com/abhinayagarwal/controlsfx/
$ cd controlsfx
$ java -version
openjdk version "16.0.1" 2021-04-20
$ ./gradlew clean build check
FAILURE: Build failed with an exception.

* What went wrong:
Could not initialize class org.codehaus.groovy.runtime.InvokerHelper
$ ./gradlew --version
------------------------------------------------------------
Gradle 6.0.1
------------------------------------------------------------
$ gradle --version
------------------------------------------------------------
Gradle 7.2
------------------------------------------------------------
$ gradle clean build check
Configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* Where:
Build file '/home/username/dev/java/controlsfx/build.gradle' line: 6

* What went wrong:
A problem occurred evaluating root project 'controlsfx'.
> Plugin with id 'maven' not found.
```

As well as with JDK 17:

``` bash
$ java -version
openjdk version "17" 2021-09-14 LTS
$ ./gradlew --version
------------------------------------------------------------
Gradle 6.0.1
------------------------------------------------------------
$ ./gradlew build check
FAILURE: Build failed with an exception.

* What went wrong:
Could not initialize class org.codehaus.groovy.runtime.InvokerHelper
```

**Comment by DaveJarvis** [comment]
1. Built https://github.com/abhinayagarwal/controlsfx/ in IntelliJ/JDK 11.
1. Gradle produced `controlsfx-8.40.18-SNAPSHOT.jar`.
1. Removed ControlsFX references inside my project's `build.gradle`.
1. Copied `controlsfx-8.40.18-SNAPSHOT.jar` into my project's `libs` directory, which is automatically added to the uberjar, classpath, etc.
1. Ran the application using JDK 17.

This resulted in an application error.

**Comment by abhinayagarwal** [comment]
Hi @DaveJarvis ,

`import com.sun.javafx.scene.control.skin.ComboBoxListViewSkin` this shouldn't exist in the latest ControlsFX code. You seem to be on the `master` branch which is still meant for JDK 8.

Please checkout `jfx-13` branch and retry.

**Comment by DaveJarvis** [comment]
> Please checkout jfx-13 branch and retry.

Smoke tested. These changes appear to work with JDK 17, thank you.
