### ISSUE TITLE
All translation files are missing from controlsfx-11.1.0.jar

### ISSUE THREAD

**Issue by pigelvy** [controlsfx/controlsfx#1405]
I don't know about the other releases but, as far as `r11.1.0` is concerned, only the default english translation file is present in `controlsfx-11.1.0.jar`.

I managed to fix the problem locally by downloading the translations I need from [transiflex.com](https://www.transifex.com/controlsfx) and adding them to my sources.

Do you confirm there is a problem with translations?

**Comment by abhinayagarwal** [comment]
Ideally, the translations should be added during the jar build step. I will check what's going on.

**Comment by pigelvy** [comment]
This seems to be the intention in `controlsfx/build.gradle` but it does not work...
