### ISSUE TITLE
ToggleSwitch doesn't receive focus when tabbing

### ISSUE THREAD

**Issue by vewert** [controlsfx/controlsfx#1414]
I have a form, with several controls including some ToggleSwitch controls. When tabbing from control to control, the ToggleSwitches don't get focus. I even tried using `.setFocusTraversable(true);` on the ToggleSwitch, but that didn't seem to help.

Is there some design reason why a ToggleSwitch shouldn't receive focus?

Thanks!

**Comment by abhinayagarwal** [comment]
I can't think of a reason why ToggleSwitch shouldn't receive focus. May be @dukke can comment?
