### ISSUE TITLE
Use TableFilter programmatically to get the filter values and restore them later

### ISSUE THREAD

**Issue by treimers** [controlsfx/controlsfx#1416]
I have got a question concerning the TableFilter API. I am using a TableFilter in my JavaFX application and I want to restore the filter settings the user has made on restart of the application.

There are several methods available to modify the filtering programmatically like

- resetFilter
- unSelectAllValues
- unselectValue
- selectValue
- selectAllValues

But I am unable to understand how to "read" the current filter the user has selected in order to persist it for later use? What do I miss and what might be the correct way to read the filter?

My environment

Java: openjdk version "15" 2020-09-15
OpenJDK Runtime Environment AdoptOpenJDK (build 15+36)
OpenJFX: 15.0.1
Controls FX: 11.1.1

Thx in advance
Thorsten

**Comment by danielpeintner** [comment]
I think it is possible to retrieve the selected values for each column.
See below a code snippet that reports which value is selected for email column. See [HelloTableFilter](https://github.com/controlsfx/controlsfx/blob/master/controlsfx-samples/src/main/java/org/controlsfx/samples/tableview/HelloTableFilter.java) Example.

```Java
            Optional<ColumnFilter<Person,?>> colFilter = tableFilter.getColumnFilter(emailCol);
            if (colFilter.isPresent()) {
                System.out.println("Email");
                for (FilterValue fv : colFilter.get().getFilterValues()) {
                    System.out.println("\t" + fv.getValue() + " -> " + fv.selectedProperty());
                }
            }
```

**Comment by treimers** [comment]
Ok, thank you for this hint.
