### ISSUE TITLE
ToggleSwitch: How to disable animation? 

### ISSUE THREAD

**Issue by javix** [controlsfx/controlsfx#1426]
There is no way to turn off animation by flag, like TitledPane. 
Unfortunately it doesn't work via css either.

```
.toggle-switch {
    -thumb-move-animation-time: 1;
}
```

**Comment by abhinayagarwal** [comment]
Is there a specific reason why you want to turn off the animation?

**Comment by abhinayagarwal** [comment]
There was a bug in the source. It will be fixed with #1434
