### ISSUE TITLE
SearchableComboBox : 100% cpu usage for JavaFX application thread

### ISSUE THREAD

**Issue by guirak** [controlsfx/controlsfx#1440]
Hello,

When I use the SearchableComboBox on my app, 1 core CPU is full used by the JavaFX application thread. 

This problem is caused by the following code in the SearchableComboBoxSkin : 

    @Override
    protected void layoutChildren(double x, double y, double w, double h) {
        super.layoutChildren(x, y, w, h);
        // ensure filteredComboBox and searchField have the same size as the field
        filteredComboBox.resizeRelocate(x, y, w, h);
        searchField.resizeRelocate(x, y, w, h);
    }

If I comment the line **filteredComboBox.resizeRelocate(x, y, w, h);**, the problem doesn't occurs.

It seems to me that the layoutChildren method is called continuously. 

Regards.

**Comment by javix** [comment]
This is really a big problem. We use several SearchableComboBox and the performance is pretty bad.
Wouldn't it make sense to call resizeRelocate in SearchableComboBoxSkin.layoutChildren only if the values x, y, w, h have changed since the last call?

**Comment by javix** [comment]
```
public class MyComboBoxSkin<T> extends SearchableComboBoxSkin<T>
{
    public MyComboBoxSkin(MyComboBox<T> comboBox)
    {
        super(comboBox);
    }

    @Override
    protected void layoutChildren(double x, double y, double w, double h) {
        System.out.println("layoutChildren: " + x + ", " + y + ", " + w + ", " + h);
        super.layoutChildren(x, y, w, h);
    }
}
```

```
public class MyComboBox<T> extends SearchableComboBox<T>
{
    @Override
    protected Skin<?> createDefaultSkin()
    {
        return new MyComboBoxSkin<>(this);
    }
}
```

Endless output:
```
layoutChildren: 0.0, 0.0, 509.0, 41.0
layoutChildren: 0.0, 0.0, 509.0, 41.0
layoutChildren: 0.0, 0.0, 509.0, 41.0
layoutChildren: 0.0, 0.0, 509.0, 41.0
layoutChildren: 0.0, 0.0, 509.0, 41.0
layoutChildren: 0.0, 0.0, 509.0, 41.0
layoutChildren: 0.0, 0.0, 509.0, 41.0
layoutChildren: 0.0, 0.0, 509.0, 41.0
layoutChildren: 0.0, 0.0, 509.0, 41.0
```

**Comment by javix** [comment]
I think the problem is because resizeRelocate is called in the layout phase. This causes layoutChildren to be called again in Parent.layout because LayoutFlag = NEEDS_LAYOUT.
See Parent.layout() line 865. 
I am using Javafx 17.0.2.

**Comment by javix** [comment]
Der Aufruf von filteredComboBox.resizeRelocate führt dazu, dass das LayoutFlag auf NEEDS_LAYOUT gesetzt wird.
![Bildschirmfoto vom 2022-10-12 14-02-02](https://user-images.githubusercontent.com/5870244/195337731-c8595e6e-6c94-461f-aedc-8105a0593b13.png)

**Comment by javix** [comment]
We urgently need a solution. Would it be enough to check if the values x, y, w, h have changed since the last call?

**Comment by abhinayagarwal** [comment]
@javix Can you test PR #1469 and see if it resolves the issue?

**Comment by javix** [comment]
I have commented out the second ComboBox in the example.

When I run the example, it prints twice for one ComboBox:
```
layoutChildren: 0.0, 0.0, 194.0, 26.0
layoutChildren: 0.0, 0.0, 194.0, 26.0
```

Each time the ComboBox is opened and closed, there is an output:
```
layoutChildren: 0.0, 0.0, 194.0, 26.0
```

When I shrink the application window, 2 outputs are made for one ComboBox:
```
layoutChildren: 0.0, 0.0, 191.0, 26.0
layoutChildren: 0.0, 0.0, 191.0, 26.0
layoutChildren: 0.0, 0.0, 189.0, 26.0
layoutChildren: 0.0, 0.0, 189.0, 26.0
layoutChildren: 0.0, 0.0, 186.0, 26.0
layoutChildren: 0.0, 0.0, 186.0, 26.0
layoutChildren: 0.0, 0.0, 178.0, 26.0
layoutChildren: 0.0, 0.0, 178.0, 26.0
layoutChildren: 0.0, 0.0, 173.0, 26.0
layoutChildren: 0.0, 0.0, 173.0, 26.0
layoutChildren: 0.0, 0.0, 172.0, 26.0
layoutChildren: 0.0, 0.0, 172.0, 26.0
```

If that's okay, and if it doesn't have any negative side effects because you didn't call super().layoutChildren, then I consider it done.
