### ISSUE TITLE
Solution for application crash on Window close, when PopOver is still open.

### ISSUE THREAD

**Issue by rhabarberbarberah** [controlsfx/controlsfx#1441]
The problem seems to be caused by the fade-duration, which will keep the PopOver visible, while the Window already closed.

You can keep your default fade-furation, if you call:
```
ownerWindowProperty().addListener((o) -> {
    if (getOwnerWindow() != null) {
        getOwnerWindow().setOnCloseRequest((t) -> {
            hide(Duration.ZERO);
        });
    }
});
```
instead.

That way it'll only disappear immediately, when the ownerWindow is closed.

_Originally posted by @rhabarberbarberah in https://github.com/controlsfx/controlsfx/issues/448#issuecomment-1120431005_

**Comment by rhabarberbarberah** [comment]
might be worth considering to add this snippet to the PopOver-Class

**Comment by abhinayagarwal** [comment]
Hi @rhabarberbarberah ,

Would you like to create a PR for this issue?

**Comment by rhabarberbarberah** [comment]
Hi, @abhinayagarwal

just created a PR: #1443
