### ISSUE TITLE
logindialog usage confusion

### ISSUE THREAD

**Issue by dragonsKnight5** [controlsfx/controlsfx#1454]
Hi,
could an additional example of how to use logindialog be provided?

the current example uses null for its arguments, when I try to use the Pair and Callback as its arguments as specified in the javadoc
I'm getting rather confused about how to implement it correctly

**Comment by eugener** [comment]
- The first argument is an optional credentials (user name and password), which will be filled as dialog is shown. 
- The second argument is a function implementing authentication algorithm. Credentials are passed into it. If no exception is thrown, authentication is considered to be successful.
