### ISSUE TITLE
Remove question symbol in WizardPane

### ISSUE THREAD

**Issue by Unaimend** [controlsfx/controlsfx#1456]
Hi, How do I remove the question mark icon on the upper left?
<img width="649" alt="Bildschirmfoto 2022-09-02 um 11 16 09" src="https://user-images.githubusercontent.com/7808379/188107116-82928918-7947-4271-b740-22887bccbbbb.png">

This view is created by extending ControlsFX WizardPane class.

Thank you for your time.

**Comment by Unaimend** [comment]
I found out that this behavior actually is implemented in the Wizard class. I still have to investigate if its possible there but I will close this issue for now.

**Comment by DaveJarvis** [comment]
One way to do this is to provide your own header to the `WizardPane`. In [KeenWrite](https://github.com/DaveJarvis/keenwrite/blob/971a60b8072d1ada66f36d69db5df104101b209c/src/main/java/com/keenwrite/typesetting/TypesetterInstaller.java#L234), this is accomplished as follows:

``` java
  private WizardPane wizardPane( final String headerKey ) {
    final var imageView = new ImageView( ICON_DIALOG );
    final var headerText = get( headerKey );
    final var headerLabel = new Label( headerText );
    headerLabel.setScaleX( 1.25 );
    headerLabel.setScaleY( 1.25 );

    final var separator = new Separator();
    separator.setPadding( new Insets( PAD, 0, 0, 0 ) );

    final var borderPane = new BorderPane();
    borderPane.setCenter( headerLabel );
    borderPane.setRight( imageView );
    borderPane.setBottom( separator );
    borderPane.setPadding( new Insets( PAD, PAD, 0, PAD ) );

    final var wizardPane = new WizardPane();
    wizardPane.setHeader( borderPane );

    return wizardPane;
  }
```

Produces:

![custom-wizard](https://user-images.githubusercontent.com/2131950/208335725-483288b3-244a-41a8-bff1-06c2b6dcc7ad.png)

**Comment by Unaimend** [comment]
Works flawlessly. Thank you very very very much. This has been bugging me for months.

**Comment by DaveJarvis** [comment]
@Unaimend -- if you find a way to change the icon in the upper-left, do let me know!
