### ISSUE TITLE
Cannot build controlsfx on Windows

### ISSUE THREAD

**Issue by KniKnaKnorke** [controlsfx/controlsfx#1464]
Hey,
I saw this  issue https://github.com/controlsfx/controlsfx/issues/1370 and the following PR https://github.com/controlsfx/controlsfx/pull/1460.

But the problem is still not fixed on my Windows system. When I try to run ./gradlew build check I still get same error as in the issue reported.

```
Execution failed for task ':controlsfx:jar'.
> java.util.ConcurrentModificationException (no error message)
```

But after upgrading biz.aQute.bnd.builde to version 5.1.2 its now working. That was the same thing which @Maxoudela tried. But back then it seems that this was not working.

**Comment by jmborer** [comment]
Hello. This is the solution to properly build the master.
