### ISSUE TITLE
Is there any way to customize button behavior of the wizard.

### ISSUE THREAD

**Issue by Unaimend** [controlsfx/controlsfx#1475]
The wizard shows three buttons by default, Previous, Next, Cancel. Is there anyway to customize the behavior of those buttons

**Comment by colinduplantis** [comment]
I've been looking into this, too. The method isn't super-easy, but, it is possible.

If you want to keep the previous, next, and cancel buttons, wait until the Flow is set on the Wizard. This is the step where those buttons are added to your WizardPane. After this step, you can dig out the ButtonBar from WizardPane.getChildren() and thereafter you can dig out the buttons from the ButtonBar.getButtons().

You can add your own behavior to these buttons. All I wanted to do was to add some validation that enabled/disabled the Next button. I suspect it would be possible to add additional listeners to the button events, though.

**Comment by Unaimend** [comment]
That's a really good idea. Thank you. I will try it out
