### ISSUE TITLE
Read-only properties in PropertySheet don't subscribe to updates from PropertySheet.Item.getObservableValue()

### ISSUE THREAD

**Issue by vatbub** [controlsfx/controlsfx#1511]
Hey,
thank you guys for this great library! It contains great, much needed controls and makes my UI life so much easier. I found a behaviour in `PropertySheet` which I didn't expect, hence, this issue. I also wrote a fix already which I will shortly submit as a PR.
Cheers,
Frederik aka. vatbub

# Expected behaviour
I created an instance of `PropertySheet`. I created a class that implements `PropertySheet.Info` (see below) and supplies its value from a read-only JavaFX-`ObservableValue`. It thus offers this `ObservableValue` also in `getObservableValue()`. When setting `override fun isEditable(): Boolean = true`, the `PropertySheet` subscribes to changes in the `ObservableValue` and updates accordingly. However, when `override fun isEditable(): Boolean = false` (because the user shall not be able to change the property value), the underlying `ObservableValue` may still change and the `PropertySheet` should update accordingly.

# Actual behaviour
`PropertySheet` does not subscribe to the  `ObservableValue` if `isEditable()` retuns `false` and thus does not reflect changes of `ObservableValue`.

# Probable solution
See attached PR

# Source code for reproduction
## ReadOnlyObservableItem.kt

```kotlin
/*
 * Copyright (c) 2023. The artifacts created for the STREEM project are currently only intended for internal use.
 * With internal use, we mean use within the university of Freiburg and Fraunhofer IPM.
 * All other use in source or binary form must be approved by Prof. Alexander Reiterer or any other representative of the university or Fraunhofer who is eligible for such an approval.
 */

package de.uni_freiburg.inatech.streem.feature_analyzer.view.property_sheet_items

import javafx.beans.value.ObservableValue
import org.controlsfx.control.PropertySheet
import java.util.*

class ReadOnlyObservableItem<T : Any>(
    private val observable: ObservableValue<T>,
    private val name: String,
    private val category: PropertyCategory,
    private val description: String = "",
    private val type: Class<T>
) : PropertySheet.Item {
    override fun getType(): Class<*> = type

    override fun getCategory(): String = category.displayName

    override fun getName(): String = name

    override fun getDescription(): String = description

    override fun getValue(): T = observable.value

    override fun setValue(value: Any?) {
        throw NotImplementedError("This value is read-only")
    }

    override fun getObservableValue(): Optional<ObservableValue<out Any>> =
        Optional.of(observable)

    override fun isEditable(): Boolean = false
}

inline fun <reified T : Any> ReadOnlyObservableItem(
    observable: ObservableValue<T>,
    name: String,
    category: PropertyCategory,
    description: String = ""
) = ReadOnlyObservableItem(observable, name, category, description, T::class.java)
```

**Comment by Siedlerchr** [comment]
Closing this as this is now resolved by your PR
