### ISSUE TITLE
Snapshot release fails due to transifex api

### ISSUE THREAD

**Issue by Siedlerchr** [controlsfx/controlsfx#1526]
Noticed that in the build run:

https://github.com/controlsfx/controlsfx/actions/runs/6663297871/job/18108945943 

> This version of API is obsolete. Please have a look at https://developers.transifex.com/reference/api-introduction for details.

https://app.transifex.com/api/2/project/controlsfx/resource/controlsfx-core?details

**Comment by Siedlerchr** [comment]
@abhinayagarwal From what I see the transifex API url is somehow defined in the secrets, so I cannot fix anything related to it.

**Comment by abhinayagarwal** [comment]
Can you drop me your Transifex username? I will add you to the project.

**Comment by Siedlerchr** [comment]
I don't have a transifex account yet, will setup one tomorrow, but thanks already for the quick fix!
