### ISSUE TITLE
Where are the previous and newer changelog ?

### ISSUE THREAD

**Issue by pseudo555** [controlsfx/controlsfx#1572]
Hello,

I'm currently using controlsfx 0.8.40 in one of my personal project.

this github only trace some versions, but not the previous ones (i mean everything between v11 is not present in https://github.com/controlsfx/controlsfx/releases)
I also notice that maven repository have a newer version (v11.2.1 - https://mvnrepository.com/artifact/org.controlsfx/controlsfx/11.2.1) than the one in this github.

The wiki page (https://github.com/controlsfx/controlsfx/wiki/Release-Versioning) is not helping, and make me more confuse : 
_In other words, ControlsFX 8.0.0 is the first release of ControlsFX to work on JavaFX 8.0 and above._ 
Where the release says 
_ControlsFX is now built using JavaFX 17. Although, it should work with earlier versions as well._
I would exopect to get a 17.xx version, not a 11.xx one.

Anyhow my question is : where can i found the real changelog of each version ? 
I just want to know what was fixed between 8.40.14 to 8.40.18.

https://github.com/controlsfx/controlsfx/compare/8.40.15...8.40.18 is a way to go, but doesn't go back enough in time.

**Comment by abhinayagarwal** [comment]
I guess those releases were done before we moved to Github or started using Github releases.

**Comment by abhinayagarwal** [comment]
Release notes for v11.2.1 are now present.

For the older versions, you can easily generate them by bisecting the commits between tags.
