### ISSUE TITLE
SpreadsheetView, strange memory behavior while scrolling

### ISSUE THREAD

**Issue by JonathanGiles** [controlsfx/controlsfx#712]
**[Original report](https://bitbucket.org/controlsfx/controlsfx/issue/521) by Alex Ivanov (Bitbucket: [Wassup741](https://bitbucket.org/Wassup741), GitHub: [Wassup741](https://github.com/Wassup741)).**

----------------------------------------

Hello. If you open controlsfx-samples-8.20.8.jar (i tried on jdk1.8.0_31) and start to scroll SpreadsheetView sample for 10-20 minutes, you will get enormous memory allocation in arrays of InvalidationListener class (memory leak perhaprs). Heap size graphic is attached

**Comment by Maxoudela** [comment]
Not a bug.
