### ISSUE TITLE
SpreadsheetView internal stylesheet is hard to override

### ISSUE THREAD

**Issue by JonathanGiles** [controlsfx/controlsfx#957]
**[Original report](https://bitbucket.org/controlsfx/controlsfx/issue/766) by Robert Ross (Bitbucket: [robross0606](https://bitbucket.org/robross0606), GitHub: [robross0606](https://github.com/robross0606)).**

----------------------------------------

SpreadSheetView does not abide by the parent application/scene stylesheet.  Instead, it is overridden by SpreadSheetGridView and CellView's use of hard-coded internal resource stylesheet.  There is also no way to override this by changing the user agent style sheet directly.  Instead, I must intentionally and specifically override every style selector used in the hard-coded stylesheet.

**Comment by Patowhiz** [comment]
I'm using [JMetro](https://www.pixelduke.com/java-javafx-theme-jmetro/)  to theme my application. The spreadsheet control shrinks the column header when I click on any row. The screenshots below show this. I can't resize the headers, what could be the issue with this?

Before the click
![1](https://user-images.githubusercontent.com/21179007/62479823-3330eb00-b763-11e9-866b-b79b37f50952.PNG)

After the click
![2](https://user-images.githubusercontent.com/21179007/62479846-3f1cad00-b763-11e9-8947-a06e5c9941d6.PNG)
